import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { test } from "node:test";
import { inflateRawSync } from "node:zlib";

import {
  BAMBU_PLATE_GCODE_PATH,
  bambuModelIdFor,
  buildBambuPlatePackage
} from "./bambuPackage";

/**
 * The plate package is what the printer's firmware opens, so these tests assert
 * its *structure*, not just that a function returned bytes. The expected layout
 * was taken from a real `.gcode.3mf` downloaded off this farm's A1.
 */

const GCODE = Buffer.from(
  "; generated by OrcaSlicer 2.3.0\n; printer_model = Bambu Lab A1\nG28\nG1 X10 Y10 E5\n".repeat(40),
  "utf8"
);

const INPUT = {
  gcode: GCODE,
  printerModelId: "N2S",
  nozzleDiameterMm: 0.4,
  material: "PETG",
  etaSeconds: 5329,
  filamentGrams: 31.1
};

/** Minimal ZIP reader: the central directory is the authority on what is inside. */
function readZip(bytes: Uint8Array): Map<string, Buffer> {
  const buf = Buffer.from(bytes);
  const eocd = buf.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  assert.ok(eocd > 0, "end-of-central-directory record must exist");
  const count = buf.readUInt16LE(eocd + 10);
  let offset = buf.readUInt32LE(eocd + 16);

  const out = new Map<string, Buffer>();
  for (let i = 0; i < count; i += 1) {
    assert.equal(buf.readUInt32LE(offset), 0x02014b50, "central directory signature");
    const method = buf.readUInt16LE(offset + 10);
    const compressedSize = buf.readUInt32LE(offset + 20);
    const uncompressedSize = buf.readUInt32LE(offset + 24);
    const nameLen = buf.readUInt16LE(offset + 28);
    const extraLen = buf.readUInt16LE(offset + 30);
    const commentLen = buf.readUInt16LE(offset + 32);
    const localOffset = buf.readUInt32LE(offset + 42);
    const name = buf.subarray(offset + 46, offset + 46 + nameLen).toString("utf8");

    const localNameLen = buf.readUInt16LE(localOffset + 26);
    const localExtraLen = buf.readUInt16LE(localOffset + 28);
    const dataStart = localOffset + 30 + localNameLen + localExtraLen;
    const raw = buf.subarray(dataStart, dataStart + compressedSize);
    const data = method === 8 ? inflateRawSync(raw) : Buffer.from(raw);
    assert.equal(data.length, uncompressedSize, `${name} inflates to its declared size`);
    out.set(name, data);
    offset += 46 + nameLen + extraLen + commentLen;
  }
  return out;
}

test("package carries every part the firmware opens, and the G-code verbatim", () => {
  const pkg = buildBambuPlatePackage(INPUT);
  const parts = readZip(pkg.bytes);

  for (const required of [
    "[Content_Types].xml",
    "_rels/.rels",
    "3D/3dmodel.model",
    BAMBU_PLATE_GCODE_PATH,
    `${BAMBU_PLATE_GCODE_PATH}.md5`,
    "Metadata/plate_1.json",
    "Metadata/slice_info.config",
    "Metadata/model_settings.config",
    "Metadata/_rels/model_settings.config.rels"
  ]) {
    assert.ok(parts.has(required), `package must contain ${required}`);
  }

  // The point of the whole exercise: the sliced bytes must survive unmodified.
  assert.deepEqual(parts.get(BAMBU_PLATE_GCODE_PATH), Buffer.from(GCODE));
});

test("the embedded md5 is the md5 of the embedded G-code, upper-case", () => {
  const pkg = buildBambuPlatePackage(INPUT);
  const parts = readZip(pkg.bytes);
  const embedded = parts.get(`${BAMBU_PLATE_GCODE_PATH}.md5`)!.toString("utf8").trim();

  assert.equal(embedded, createHash("md5").update(GCODE).digest("hex").toUpperCase());
  assert.equal(embedded, pkg.gcodeMd5);
  assert.match(embedded, /^[0-9A-F]{32}$/);
});

test("relationships point only at parts that exist", () => {
  // A relationship to an absent thumbnail is exactly the kind of malformed
  // package a firmware may reject, so the writer must not emit one.
  const parts = readZip(buildBambuPlatePackage(INPUT).bytes);
  const rels = parts.get("_rels/.rels")!.toString("utf8");

  for (const target of [...rels.matchAll(/Target="\/([^"]+)"/g)].map((m) => m[1])) {
    assert.ok(parts.has(target), `_rels/.rels points at ${target}, which must be in the package`);
  }
  assert.ok(!rels.includes(".png"), "no thumbnail relationships when no thumbnails are written");
});

test("slice metadata reports the target model, nozzle and filament", () => {
  const parts = readZip(buildBambuPlatePackage(INPUT).bytes);
  const info = parts.get("Metadata/slice_info.config")!.toString("utf8");

  assert.match(info, /printer_model_id" value="N2S"/);
  assert.match(info, /nozzle_diameters" value="0\.4"/);
  assert.match(info, /type="PETG"/);
  assert.match(info, /prediction" value="5329"/);

  const plate = JSON.parse(parts.get("Metadata/plate_1.json")!.toString("utf8"));
  assert.equal(plate.nozzle_diameter, 0.4);
});

test("packaging is deterministic — the same slice always yields the same bytes", () => {
  // This is what keeps `prepare` idempotent: a re-prepare must not produce a
  // different file for the same job, or every retry would look like new content.
  const a = buildBambuPlatePackage(INPUT);
  const b = buildBambuPlatePackage({ ...INPUT });
  assert.deepEqual(Buffer.from(a.bytes), Buffer.from(b.bytes));
});

test("a different slice yields different bytes", () => {
  const a = buildBambuPlatePackage(INPUT);
  const b = buildBambuPlatePackage({ ...INPUT, gcode: Buffer.from(`${GCODE.toString()}G1 X1\n`) });
  assert.notDeepEqual(Buffer.from(a.bytes), Buffer.from(b.bytes));
});

test("no ZIP64 records for a normal plate — strict readers must cope", () => {
  const buf = Buffer.from(buildBambuPlatePackage(INPUT).bytes);
  assert.equal(buf.indexOf(Buffer.from([0x50, 0x4b, 0x06, 0x06])), -1, "no ZIP64 EOCD");
  assert.equal(buf.indexOf(Buffer.from([0x50, 0x4b, 0x06, 0x07])), -1, "no ZIP64 locator");
});

test("XML is escaped, so a hostile material name cannot break the package", () => {
  const parts = readZip(
    buildBambuPlatePackage({ ...INPUT, material: 'PETG"><inject/>' }).bytes
  );
  const info = parts.get("Metadata/slice_info.config")!.toString("utf8");
  assert.ok(!info.includes("<inject/>"), "injected markup must be escaped");
  assert.match(info, /&quot;&gt;&lt;inject\/&gt;/);
});

test("Bambu model ids map from catalogue codes, and refuse to guess", () => {
  assert.equal(bambuModelIdFor("bambu-a1"), "N2S");
  assert.equal(bambuModelIdFor("bambu-a1-mini"), "N1");
  assert.equal(bambuModelIdFor("bambu-p1s"), "C12");
  // An unknown model yields null so the caller refuses, rather than shipping a
  // package that claims to be for the wrong machine.
  assert.equal(bambuModelIdFor("creality-k2-plus"), null);
  assert.equal(bambuModelIdFor(null), null);
});
