import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { test } from "node:test";
import { inflateRawSync } from "node:zlib";

import {
  BAMBU_PLATE_GCODE_PATH,
  bambuModelIdFor,
  buildBambuPlatePackage
} from "./bambuPackage";

/**
 * The plate package is what the printer's firmware opens, so these tests assert
 * its *structure*, not just that a function returned bytes. The expected layout
 * was taken from a real `.gcode.3mf` downloaded off this farm's A1.
 */

const GCODE = Buffer.from(
  "; generated by OrcaSlicer 2.3.0\n; printer_model = Bambu Lab A1\nG28\nG1 X10 Y10 E5\n".repeat(40),
  "utf8"
);

const INPUT = {
  gcode: GCODE,
  printerModelId: "N2S",
  nozzleDiameterMm: 0.4,
  material: "PETG",
  etaSeconds: 5329,
  filamentGrams: 31.1
};

/** Minimal ZIP reader: the central directory is the authority on what is inside. */
function readZip(bytes: Uint8Array): Map<string, Buffer> {
  const buf = Buffer.from(bytes);
  const eocd = buf.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  assert.ok(eocd > 0, "end-of-central-directory record must exist");
  const count = buf.readUInt16LE(eocd + 10);
  let offset = buf.readUInt32LE(eocd + 16);

  const out = new Map<string, Buffer>();
  for (let i = 0; i < count; i += 1) {
    assert.equal(buf.readUInt32LE(offset), 0x02014b50, "central directory signature");
    const method = buf.readUInt16LE(offset + 10);
    const compressedSize = buf.readUInt32LE(offset + 20);
    const uncompressedSize = buf.readUInt32LE(offset + 24);
    const nameLen = buf.readUInt16LE(offset + 28);
    const extraLen = buf.readUInt16LE(offset + 30);
    const commentLen = buf.readUInt16LE(offset + 32);
    const localOffset = buf.readUInt32LE(offset + 42);
    const name = buf.subarray(offset + 46, offset + 46 + nameLen).toString("utf8");

    const localNameLen = buf.readUInt16LE(localOffset + 26);
    const localExtraLen = buf.readUInt16LE(localOffset + 28);
    const dataStart = localOffset + 30 + localNameLen + localExtraLen;
    const raw = buf.subarray(dataStart, dataStart + compressedSize);
    const data = method === 8 ? inflateRawSync(raw) : Buffer.from(raw);
    assert.equal(data.length, uncompressedSize, `${name} inflates to its declared size`);
    out.set(name, data);
    offset += 46 + nameLen + extraLen + commentLen;
  }
  return out;
}

test("package carries every part the firmware opens, and the G-code verbatim", async () => {
  const pkg = await buildBambuPlatePackage(INPUT);
  const parts = readZip(pkg.bytes);

  for (const required of [
    "[Content_Types].xml",
    "_rels/.rels",
    "3D/3dmodel.model",
    BAMBU_PLATE_GCODE_PATH,
    `${BAMBU_PLATE_GCODE_PATH}.md5`,
    "Metadata/plate_1.json",
    "Metadata/slice_info.config",
    "Metadata/model_settings.config",
    "Metadata/_rels/model_settings.config.rels"
  ]) {
    assert.ok(parts.has(required), `package must contain ${required}`);
  }

  // The point of the whole exercise: the sliced bytes must survive unmodified.
  assert.deepEqual(parts.get(BAMBU_PLATE_GCODE_PATH), Buffer.from(GCODE));
});

test("the embedded md5 is the md5 of the embedded G-code, upper-case", async () => {
  const pkg = await buildBambuPlatePackage(INPUT);
  const parts = readZip(pkg.bytes);
  const embedded = parts.get(`${BAMBU_PLATE_GCODE_PATH}.md5`)!.toString("utf8").trim();

  assert.equal(embedded, createHash("md5").update(GCODE).digest("hex").toUpperCase());
  assert.equal(embedded, pkg.gcodeMd5);
  assert.match(embedded, /^[0-9A-F]{32}$/);
});

test("relationships point only at parts that exist", async () => {
  // A relationship to an absent thumbnail is exactly the kind of malformed
  // package a firmware may reject, so the writer must not emit one.
  const parts = readZip((await buildBambuPlatePackage(INPUT)).bytes);
  const rels = parts.get("_rels/.rels")!.toString("utf8");

  for (const target of [...rels.matchAll(/Target="\/([^"]+)"/g)].map((m) => m[1])) {
    assert.ok(parts.has(target), `_rels/.rels points at ${target}, which must be in the package`);
  }
  assert.ok(!rels.includes(".png"), "no thumbnail relationships when no thumbnails are written");
});

test("slice metadata reports the target model, nozzle and filament", async () => {
  const parts = readZip((await buildBambuPlatePackage(INPUT)).bytes);
  const info = parts.get("Metadata/slice_info.config")!.toString("utf8");

  assert.match(info, /printer_model_id" value="N2S"/);
  assert.match(info, /nozzle_diameters" value="0\.4"/);
  assert.match(info, /type="PETG"/);
  assert.match(info, /prediction" value="5329"/);

  const plate = JSON.parse(parts.get("Metadata/plate_1.json")!.toString("utf8"));
  assert.equal(plate.nozzle_diameter, 0.4);
});

test("packaging is deterministic — the same slice always yields the same bytes", async () => {
  // This is what keeps `prepare` idempotent: a re-prepare must not produce a
  // different file for the same job, or every retry would look like new content.
  const a = await buildBambuPlatePackage(INPUT);
  const b = await buildBambuPlatePackage({ ...INPUT });
  assert.deepEqual(Buffer.from(a.bytes), Buffer.from(b.bytes));
});

test("a different slice yields different bytes", async () => {
  const a = await buildBambuPlatePackage(INPUT);
  const b = await buildBambuPlatePackage({ ...INPUT, gcode: Buffer.from(`${GCODE.toString()}G1 X1\n`) });
  assert.notDeepEqual(Buffer.from(a.bytes), Buffer.from(b.bytes));
});

test("no ZIP64 records for a normal plate — strict readers must cope", async () => {
  const buf = Buffer.from((await buildBambuPlatePackage(INPUT)).bytes);
  assert.equal(buf.indexOf(Buffer.from([0x50, 0x4b, 0x06, 0x06])), -1, "no ZIP64 EOCD");
  assert.equal(buf.indexOf(Buffer.from([0x50, 0x4b, 0x06, 0x07])), -1, "no ZIP64 locator");
});

test("XML is escaped, so a hostile material name cannot break the package", async () => {
  const parts = readZip(
    (await buildBambuPlatePackage({ ...INPUT, material: 'PETG"><inject/>' })).bytes
  );
  const info = parts.get("Metadata/slice_info.config")!.toString("utf8");
  assert.ok(!info.includes("<inject/>"), "injected markup must be escaped");
  assert.match(info, /&quot;&gt;&lt;inject\/&gt;/);
});

test("Bambu model ids map from catalogue codes, and refuse to guess", () => {
  assert.equal(bambuModelIdFor("bambu-a1"), "N2S");
  assert.equal(bambuModelIdFor("bambu-a1-mini"), "N1");
  assert.equal(bambuModelIdFor("bambu-p1s"), "C12");
  // An unknown model yields null so the caller refuses, rather than shipping a
  // package that claims to be for the wrong machine.
  assert.equal(bambuModelIdFor("creality-k2-plus"), null);
  assert.equal(bambuModelIdFor(null), null);
});

// ── Cost of building a package ──────────────────────────────────────────────
//
// The compression used to be `deflateRawSync`, which blocks the WHOLE event
// loop: 154 ms for a 10 MB slice, 837 ms for a 50 MB one, measured on this
// farm's hardware. Nothing else runs in that window — no printer poll, no HTTP
// response, no monitoring-lease renewal — and it happens in the middle of a
// launch, which is exactly when the dashboard is watching.

/*
 * Both stall tests below used a bare wall-clock bound, and a bare bound measures
 * the machine as much as the code: with the rest of this suite, a browser
 * container and a build sharing the box, the idle loop alone drifts tens of
 * milliseconds and the test fails for a reason that has nothing to do with
 * compression. That is the failure mode that teaches a team to ignore red tests
 * — this suite spent months carrying 38 "expected" ones.
 *
 * So each now asserts the invariant it actually claims, as a RATIO, which is
 * machine-independent because load inflates both sides together:
 *
 *   - one synchronous pass must not dominate the build (worst gap vs build time);
 *   - the stall must not scale with the file (40 MB gap vs 4 MB gap).
 *
 * Both still fail decisively on the regression they exist for: the unchunked
 * code spent essentially the *whole* build inside one block (154 ms of a 160 ms
 * 10 MB build) and grew linearly with the input (>200 ms at 40 MB against ~30 ms
 * at 4 MB).
 */

test("building a package does not block the event loop", async (t) => {
  // A realistic sliced body: large and highly repetitive, as G-code is.
  const line = "G1 X120.456 Y98.765 E.03338\n";
  const gcode = Buffer.from(line.repeat(Math.ceil((10 * 1024 * 1024) / line.length)), "utf8");

  // A 10 ms interval stands in for the poll loop; the worst gap it experiences
  // while the package is built is the stall a printer would have seen.
  let worstGapMs = 0;
  let last = process.hrtime.bigint();
  const probe = setInterval(() => {
    const now = process.hrtime.bigint();
    worstGapMs = Math.max(worstGapMs, Number(now - last) / 1e6 - 10);
    last = now;
  }, 10);

  let pkg;
  let buildMs = 0;
  try {
    await new Promise((resolve) => setTimeout(resolve, 30));
    last = process.hrtime.bigint();
    const started = process.hrtime.bigint();
    pkg = await buildBambuPlatePackage({ ...INPUT, gcode });
    buildMs = Number(process.hrtime.bigint() - started) / 1e6;
    await new Promise((resolve) => setTimeout(resolve, 30));
  } finally {
    clearInterval(probe);
  }

  // The original fixed 80 ms, WIDENED by a share of the build — never narrowed.
  // A chunked build spends its worst single gap on one chunk (a few percent),
  // while the synchronous form spent ~154 ms of a ~160 ms build inside one
  // block, so half the build is a bound the regression cannot pass and a slow
  // machine cannot trip. The fixed floor is what protects a *fast* build, where
  // half of it is less than a stray GC pause.
  const budget = Math.max(80, buildMs * 0.5);
  t.diagnostic(
    `10 MB package: build ${buildMs.toFixed(0)} ms, worst event-loop gap ` +
      `${worstGapMs.toFixed(0)} ms (budget ${budget.toFixed(0)} ms)`
  );
  assert.ok(pkg.bytes.byteLength > 0);
  assert.ok(
    worstGapMs < budget,
    `one gap of ${worstGapMs.toFixed(0)} ms out of a ${buildMs.toFixed(0)} ms build ` +
      "— compression is back on the main thread"
  );
});

test("moving compression off the loop did not change a single byte", async () => {
  // Determinism is what makes `prepare` idempotent: a re-prepared delivery must
  // produce the same bytes, or every size comparison reads as a bad transfer.
  const a = await buildBambuPlatePackage(INPUT);
  const b = await buildBambuPlatePackage({ ...INPUT });
  assert.equal(Buffer.compare(Buffer.from(a.bytes), Buffer.from(b.bytes)), 0);
  assert.equal(a.gcodeMd5, b.gcodeMd5);
});

/**
 * Measures the worst uninterrupted stretch the loop spends unable to run a timer
 * while `build` executes. A 2 ms probe stands in for the poll loop.
 */
async function worstLoopGapMs(build: () => Promise<unknown>): Promise<number> {
  let worst = 0;
  let last = process.hrtime.bigint();
  const probe = setInterval(() => {
    const now = process.hrtime.bigint();
    worst = Math.max(worst, Number(now - last) / 1e6 - 2);
    last = now;
  }, 2);
  try {
    await new Promise((resolve) => setTimeout(resolve, 50));
    last = process.hrtime.bigint();
    await build();
  } finally {
    clearInterval(probe);
  }
  return worst;
}

test("the stall does not grow with the file — every whole-buffer pass is chunked", async (t) => {
  // Moving the *deflate* off the loop was only part of it. Three synchronous
  // whole-buffer passes stayed behind and, at 50 MB, cost more together than the
  // deflate ever had: CRC-32 (256 ms — a byte-at-a-time JS loop), MD5 (159 ms:
  // native is not the same as concurrent) and a `Buffer.from` copy of the G-code
  // that served no purpose at all (147 ms).
  //
  // The invariant that catches all three, and any future fourth, is that the
  // worst stall must NOT scale with the file. A pass left unchunked shows up as
  // a gap that grows with the input; a chunked one stays flat.
  const line = "G1 X120.456 Y98.765 E.03338\n";
  const gcodeOf = (bytes: number) => Buffer.from(line.repeat(Math.ceil(bytes / line.length)), "utf8");
  // Built up front: allocating a 40 MB string blocks the loop all by itself, and
  // measuring the fixture instead of the subject is how a timing test lies.
  const smallGcode = gcodeOf(4 * 1024 * 1024);
  const largeGcode = gcodeOf(40 * 1024 * 1024);

  const small = await worstLoopGapMs(() => buildBambuPlatePackage({ ...INPUT, gcode: smallGcode }));
  const large = await worstLoopGapMs(() => buildBambuPlatePackage({ ...INPUT, gcode: largeGcode }));
  // Ten times the bytes must not mean ten times the stall. The original fixed
  // 120 ms stands as the floor; the 4 MB gap only ever WIDENS it, because
  // whatever is interfering with the big measurement interfered with the small
  // one too. So a loaded host stops producing false failures without the quiet
  // case getting stricter — and the regression (>200 ms at 40 MB against ~30 ms
  // at 4 MB) fails either way.
  const budget = Math.max(120, small * 4);
  t.diagnostic(
    `worst event-loop gap: 4 MB → ${small.toFixed(0)} ms, 40 MB → ${large.toFixed(0)} ms ` +
      `(budget ${budget.toFixed(0)} ms)`
  );
  assert.ok(
    large < budget,
    `40 MB stalled the loop ${large.toFixed(0)} ms against ${small.toFixed(0)} ms at 4 MB ` +
      "— the stall scales with the file, so a whole-buffer pass is back on the main thread"
  );
});

test("chunking the digests did not change them — the printer checks this md5", async () => {
  // `plate_1.gcode.md5` is verified by the firmware, and the CRC-32 by any ZIP
  // reader. Both are computed a chunk at a time now, so the thing worth pinning
  // is that a chunked digest is the same digest.
  const line = "G1 X120.456 Y98.765 E.03338\n";
  for (const bytes of [0, 1, 255 * 1024, 256 * 1024, 256 * 1024 + 1, 3 * 1024 * 1024 + 7]) {
    const gcode = Buffer.from(line.repeat(Math.ceil(bytes / line.length))).subarray(0, bytes);
    const pkg = await buildBambuPlatePackage({ ...INPUT, gcode });
    assert.equal(
      pkg.gcodeMd5,
      createHash("md5").update(gcode).digest("hex").toUpperCase(),
      `md5 of a ${bytes}-byte slice must not depend on how it was fed in`
    );
    // And the archive still reads back, which is the CRC-32 being right.
    assert.equal(Buffer.compare(readZip(pkg.bytes).get(BAMBU_PLATE_GCODE_PATH)!, gcode), 0);
  }
});

test("a G-code that does not compress is stored, not grown", async () => {
  // The `stored` fallback is the one branch that puts the raw buffer into the
  // archive rather than the deflated one. Incompressible bytes take it, and the
  // entry must still come back verbatim.
  const gcode = Buffer.alloc(64 * 1024);
  for (let i = 0; i < gcode.length; i += 1) gcode[i] = (i * 2654435761) % 251;
  const pkg = await buildBambuPlatePackage({ ...INPUT, gcode });
  assert.equal(Buffer.compare(readZip(pkg.bytes).get(BAMBU_PLATE_GCODE_PATH)!, gcode), 0);
  assert.equal(pkg.gcodeMd5, createHash("md5").update(gcode).digest("hex").toUpperCase());
});
