import type { FileHandle } from "node:fs/promises";

import type { DetectedFormat } from "../../../domain/print/types";

/**
 * Content-based format detection. The file *name* is never trusted as the source
 * of truth (the brief: "Не доверяй только расширению файла") — the format is
 * decided from magic bytes and internal structure, and the declared extension is
 * only compared against the result to surface a *mismatch*.
 *
 * Signals, in the order they are decisive:
 *   - ZIP magic (`PK\x03\x04`) → a `3mf` candidate (the real 3MF check happens in
 *     the 3MF analyzer, which opens the archive);
 *   - the exact binary-STL size identity `84 + n·50 === fileSize` → binary STL,
 *     checked *before* the text sniff so a binary file whose 80-byte header
 *     happens to begin with "solid" is not mistaken for ASCII STL;
 *   - a leading `solid` with `facet`/`vertex` markers → ASCII STL;
 *   - G/M/T command lines or a slicer header comment → G-code;
 *   - otherwise `unknown`.
 */

export interface DetectionResult {
  format: DetectedFormat;
  /** The lower-cased extension from the file name (without the dot), or null. */
  declaredExt: string | null;
  /** True when the declared extension disagrees with the detected content. */
  extMismatch: boolean;
  /** For STL, which concrete variant the magic bytes indicated. */
  stlVariant?: "binary" | "ascii";
}

const SNIFF_BYTES = 8192;
const ZIP_MAGIC = Buffer.from([0x50, 0x4b, 0x03, 0x04]); // "PK\x03\x04"
const EXT_TO_FORMAT: Record<string, DetectedFormat> = {
  stl: "stl",
  "3mf": "3mf",
  gcode: "gcode",
  gco: "gcode",
  g: "gcode"
};

export async function detectFormat(
  handle: FileHandle,
  sizeBytes: number,
  fileName: string
): Promise<DetectionResult> {
  const head = Buffer.allocUnsafe(Math.min(SNIFF_BYTES, sizeBytes));
  if (head.length > 0) {
    await handle.read(head, 0, head.length, 0);
  }
  const declaredExt = extractExt(fileName);

  const { format, stlVariant } = sniff(head, sizeBytes);
  const expected = declaredExt ? EXT_TO_FORMAT[declaredExt] : undefined;
  const extMismatch = expected !== undefined ? expected !== format : format === "unknown";

  return { format, declaredExt, extMismatch, stlVariant };
}

function sniff(head: Buffer, sizeBytes: number): { format: DetectedFormat; stlVariant?: "binary" | "ascii" } {
  if (head.length >= 4 && head.subarray(0, 4).equals(ZIP_MAGIC)) {
    return { format: "3mf" };
  }

  // Binary STL: the size is an exact function of the triangle count. This is the
  // most reliable STL signal and must be tried before the "solid" text check.
  if (sizeBytes >= 84 && head.length >= 84) {
    const count = head.readUInt32LE(80);
    if (84 + count * 50 === sizeBytes) {
      return { format: "stl", stlVariant: "binary" };
    }
  }

  const text = head.toString("latin1");
  const trimmed = text.replace(/^[\s﻿]+/, "");

  if (/^solid/i.test(trimmed) && /\bfacet\b/i.test(text) && /\bvertex\b/i.test(text)) {
    return { format: "stl", stlVariant: "ascii" };
  }

  if (looksLikeGcode(text)) {
    return { format: "gcode" };
  }

  return { format: "unknown" };
}

/** True when the head reads as G-code: motion/command lines or a slicer banner. */
function looksLikeGcode(text: string): boolean {
  if (/;\s*(generated by|sliced by|flavor:|prusaslicer|superslicer|orcaslicer|cura|bambustudio|simplify3d)/i.test(text)) {
    return true;
  }
  const lines = text.split(/\r?\n/, 200);
  let commandLines = 0;
  for (const line of lines) {
    const code = line.trim();
    if (code === "" || code.startsWith(";")) continue;
    if (/^(G0|G1|G28|G29|G90|G91|G92|G20|G21|M\d{1,3}|T\d)\b/.test(code)) commandLines++;
  }
  return commandLines >= 3;
}

function extractExt(fileName: string): string | null {
  const base = fileName.split(/[\\/]/).pop() ?? fileName;
  const dot = base.lastIndexOf(".");
  if (dot <= 0 || dot === base.length - 1) return null;
  return base.slice(dot + 1).toLowerCase();
}
