import assert from "node:assert/strict";
import fs from "node:fs";
import { afterEach, beforeEach, test } from "node:test";

import { makeGcode, tempDir, writeFixture } from "../testkit/fixtures";
import { analyzeGcode } from "./gcode";

let dir: string;
beforeEach(() => {
  dir = tempDir();
});
afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

function run(name: string, gcode: string) {
  const { path } = writeFixture(dir, name, gcode);
  return analyzeGcode(path);
}

test("extracts slicer, material, estimates and bounding box → schedulable", async () => {
  const r = await run("part.gcode", makeGcode());
  assert.equal(r.detectedFormat, "gcode");
  assert.equal(r.material, "PLA");
  assert.equal(r.layerHeightMm, 0.2);
  assert.equal(r.nozzleDiameterMm, 0.4);
  assert.equal(r.estimatedDurationS, 1 * 3600 + 5 * 60 + 12);
  assert.equal(r.estimatedFilamentG, 12.5);
  assert.equal((r.data.slicer as string), "PrusaSlicer");
  assert.equal(r.data.printerModel, "MK4");
  const bbox = r.data.bbox as { size: number[]; confidence: string };
  assert.deepEqual(bbox.size, [50, 40, 0]);
  assert.equal(bbox.confidence, "high");
  assert.equal(r.verdict, "schedulable");
});

test("relative moves (G91) are added to the running position", async () => {
  const r = await run(
    "rel.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G92 X0 Y0 Z0", "G1 X10 Y0", "G91", "G1 X5", "G1 X-20"]
    })
  );
  const bbox = r.data.bbox as { min: number[]; max: number[] };
  // abs 10 → +5 → 15 → -20 → -5. Bounds: min x -5, max x 15.
  assert.equal(bbox.min[0], -5);
  assert.equal(bbox.max[0], 15);
});

test("G92 renames the current position (origin offset) for later absolute moves", async () => {
  const r = await run(
    "g92.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G1 X10 Y10", "G92 X0 Y0", "G1 X5 Y0"]
    })
  );
  const bbox = r.data.bbox as { max: number[] };
  // After G92 X0 at physical 10, an absolute X5 maps to physical 15.
  assert.equal(bbox.max[0], 15);
});

test("inch units (G20) are converted to millimetres with a warning", async () => {
  const r = await run(
    "inch.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G20", "G90", "G1 X1 Y0"]
    })
  );
  const bbox = r.data.bbox as { max: number[] };
  assert.ok(Math.abs(bbox.max[0] - 25.4) < 1e-6);
  assert.ok(r.warnings.some((w) => w.code === "gcode_inch_units"));
});

test("arcs lower the bbox confidence and warn", async () => {
  const r = await run(
    "arc.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G1 X0 Y0", "G2 X10 Y10 I5 J0"]
    })
  );
  const bbox = r.data.bbox as { confidence: string };
  assert.equal(bbox.confidence, "medium");
  assert.ok(r.warnings.some((w) => w.code === "gcode_arcs"));
});

test("a forbidden config-mutating command (M502) blocks the file outright", async () => {
  const r = await run(
    "risky.gcode",
    makeGcode({ moves: ["G21", "G90", "M502", "G1 X10 Y10"] })
  );
  assert.equal(r.verdict, "blocked");
  assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command" && /M502/.test(b.message)));
});

test("an attended-only command (M600) forces review, not blocked", async () => {
  const r = await run(
    "swap.gcode",
    makeGcode({ moves: ["G21", "G90", "M600", "G1 X10 Y10"] })
  );
  assert.equal(r.verdict, "review");
  assert.ok(r.warnings.some((w) => w.code === "gcode_risky_command" && /M600/.test(w.message)));
});

test("firmware/file-system commands are forbidden: M997, M30, SAVE_CONFIG", async () => {
  for (const cmd of ["M997", "M30 old.gcode", "SAVE_CONFIG"]) {
    const r = await run(
      "danger.gcode",
      makeGcode({ moves: ["G21", "G90", cmd, "G1 X10 Y10"] })
    );
    assert.equal(r.verdict, "blocked", cmd);
    assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command"), cmd);
  }
});

test("unknown slicer + unknown target → review, never auto-safe", async () => {
  const r = await run("bare.gcode", ["G21", "G90", "G1 X0 Y0", "G1 X30 Y20"].join("\n"));
  assert.equal(r.verdict, "review");
  assert.ok(r.warnings.some((w) => w.code === "gcode_unknown_slicer"));
  assert.ok(r.warnings.some((w) => w.code === "gcode_unknown_target"));
});

test("a large G-code is analysed by streaming (no whole-file load)", async () => {
  const header = ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"];
  const moves: string[] = ["G21", "G90"];
  for (let i = 0; i < 40000; i++) {
    moves.push(`G1 X${i % 200} Y${(i * 7) % 150} E${i * 0.01}`);
  }
  const r = await run("big.gcode", makeGcode({ header, moves }));
  const bbox = r.data.bbox as { max: number[] };
  assert.equal(bbox.max[0], 199);
  assert.equal(bbox.max[1], 149);
  assert.equal(r.data.motionCommands, 40000);
});

// ── Bambu Lab: the vendor's own start G-code, end to end ────────────────────
//
// Reproduces the shape of a real OrcaSlicer-for-A1 file: an off-bed purge line, the
// stock levelling block with its `M500`, and an object bracketed by the slicer's own
// markers. This is the file that used to come out of the pipeline `blocked`.

const A1_HEADER = [
  "; generated by OrcaSlicer 2.3.0 on 2026-08-14 at 07:11:45",
  "; printer_model = Bambu Lab A1",
  "; filament_type = PETG",
  "; layer_height = 0.2",
  "; nozzle_diameter = 0.4",
  "; printable_area = 0x0,256x0,256x256,0x256"
];

/** Machine preamble: purge line at Y-0.5 (off the bed) + the levelling block. */
const A1_PREAMBLE = [
  "G21",
  "G90",
  "M83",
  "M204 S6000",
  "G1 X108 Y-0.5 Z0.3 F30000",
  "G1 X153 Y-0.5 E4.9 F6000 ; nozzle load line, deliberately off the bed",
  "M1002 judge_flag g29_before_print_flag",
  "G29.2 S1",
  "M622 J1",
  "    M1002 gcode_claim_action : 1",
  "    G29 A1 X109.562 Y59.325 I32.975 J137.35",
  "    M400",
  "    M500 ; save cali data",
  "M623"
];

/** A 30×30 object at X110..140 / Y60..90, wrapped in the object markers. */
const A1_OBJECT = [
  "; start printing object, unique label id: 8",
  "G1 X110 Y60 Z0.2 F3000",
  "G1 X140 Y60 E1.5",
  "G1 X140 Y90 E1.5",
  "G1 X110 Y90 E1.5",
  "G1 X110 Y60 E1.5",
  "; stop printing object, unique label id: 8"
];

function a1Gcode(extra: { beforeLevelling?: string[]; inObject?: string[] } = {}) {
  return [
    ...A1_HEADER,
    ...(extra.beforeLevelling ?? []),
    ...A1_PREAMBLE,
    ...A1_OBJECT.slice(0, 1),
    ...(extra.inObject ?? []),
    ...A1_OBJECT.slice(1),
    ""
  ].join("\n");
}

test("Bambu A1: the stock levelling M500 does not block the file", async () => {
  const r = await run("a1.gcode", a1Gcode());
  assert.deepEqual(r.blockers, []);
  assert.equal(r.verdict, "schedulable");
  assert.ok(r.warnings.some((w) => w.code === "gcode_vendor_calibration_save"));
  assert.equal(r.data.printerModel, "Bambu Lab A1");
  assert.equal(r.material, "PETG");
});

test("Bambu A1: a settings mutation ahead of the levelling block still blocks", async () => {
  const r = await run("a1-tampered.gcode", a1Gcode({ beforeLevelling: ["M92 E9999"] }));
  assert.equal(r.verdict, "blocked");
  assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command" && /M500/.test(b.message)));
});

test("bbox measures the object, not the machine's off-bed purge and parking", async () => {
  const r = await run("a1-bbox.gcode", a1Gcode());
  const bbox = r.data.bbox as { min: number[]; max: number[]; size: number[] };
  // The object only: X110..140, Y60..90. The purge line at X108..153 / Y-0.5 is
  // off the bed, and the travel to it deposits nothing.
  assert.deepEqual(bbox.min, [110, 60, 0.2]);
  assert.deepEqual(bbox.max, [140, 90, 0.2]);
  assert.deepEqual(bbox.size, [30, 30, 0]);
  assert.equal(r.data.bboxBasis, "object");
  assert.ok(r.warnings.some((w) => w.code === "gcode_purge_outside_bed"));

  // The raw toolpath is still reported beside it — nothing is hidden, only
  // attributed correctly.
  const toolpath = r.data.toolpathBbox as { min: number[]; max: number[] };
  assert.equal(toolpath.min[1], -0.5);
  assert.equal(toolpath.max[0], 153);
});

test("the mid-print filament flush is excluded from the object's box", async () => {
  // A toolchange happens *inside* the object markers and wipes at X-48.2 — the
  // reason object markers alone are not enough to bound the model.
  const r = await run(
    "a1-flush.gcode",
    a1Gcode({ inObject: ["G1 X-48.2 Y128 F18000", "G1 X-38.2 Y128 E40 ; flush", "G1 X110 Y60 F18000"] })
  );
  const bbox = r.data.bbox as { min: number[]; max: number[] };
  assert.deepEqual(bbox.min, [110, 60, 0.2]);
  assert.deepEqual(bbox.max, [140, 90, 0.2]);
});

test("Bambu pseudo-tools (T255 park, T1000 AMS unload) are not counted as extruders", async () => {
  const r = await run("a1-tools.gcode", a1Gcode({ inObject: ["T1000", "T0", "T255"] }));
  assert.equal(r.data.toolCount, 1);
});

test("a file with no object markers falls back to everything it extrudes", async () => {
  const r = await run(
    "plain.gcode",
    makeGcode({ moves: ["G21", "G90", "G1 X5 Y5 Z0.2", "G1 X60 Y45 E3", "G1 X200 Y200 F9000"] })
  );
  const bbox = r.data.bbox as { max: number[] };
  // The trailing travel to (200,200) deposits nothing, so it is not the model.
  assert.equal(r.data.bboxBasis, "extrusion");
  assert.deepEqual(bbox.max, [60, 45, 0.2]);
});

test("axis values without a leading zero are read (OrcaSlicer writes E.03338, Z.3)", async () => {
  // Not a corner case: OrcaSlicer omits the leading zero on fractions, so 94 731 of
  // the 96 480 E words in a real A1 file take this form. A pattern that demands a
  // digit before the point sees ~2 % of the extrusion and measures the model from
  // that sample.
  const r = await run(
    "leading-dot.gcode",
    [
      "; generated by OrcaSlicer 2.3.0",
      "; printer_model = Bambu Lab A1",
      "; filament_type = PETG",
      "; printable_area = 0x0,256x0,256x256,0x256",
      "G21",
      "G90",
      "M83",
      "G1 X100 Y100 Z.3 F3000",
      "G1 X130.307 Y153.795 E.0004",
      "G1 X129.752 Y154.476 E.03338",
      "G1 X.5 Y.25 E.5",
      "G1 X-.5 Y-.25 E.5",
      ""
    ].join("\n")
  );
  const bbox = r.data.bbox as { min: number[]; max: number[] };
  // The model's box: `Z.3` is read as the layer height, and the extruded extremes
  // bound it. The `X-.5 Y-.25` move is off the declared bed, so it is correctly
  // *not* part of the model…
  assert.deepEqual(bbox.min, [0.5, 0.25, 0.3]);
  assert.deepEqual(bbox.max, [130.307, 154.476, 0.3]);
  // …but it was still parsed, which the unfiltered toolpath box shows.
  const toolpath = r.data.toolpathBbox as { min: number[] };
  assert.deepEqual(toolpath.min, [-0.5, -0.25, 0.3], "negative leading-dot values are read");
});

test("a trailing-point value (X5.) is read rather than dropped", async () => {
  const r = await run(
    "trailing-dot.gcode",
    makeGcode({ moves: ["G21", "G90", "G1 X0 Y0 Z0.2", "G1 X5. Y7. E1"] })
  );
  const bbox = r.data.bbox as { max: number[] };
  assert.deepEqual(bbox.max.slice(0, 2), [5, 7]);
});

// ── Duration formats ─────────────────────────────────────────────────────────
//
// Every slicer in scope writes a day component once a print passes 24 hours, and
// dropping it turned a 26-hour job into a 2-hour one. That number is the ETA the
// scheduler fits into the night window, so the error did not stay in the parser:
// a multi-day print was planned as if it finished before dawn.

const DURATIONS: { form: string; text: string; seconds: number }[] = [
  { form: "PrusaSlicer h/m/s", text: "1h 5m 12s", seconds: 3912 },
  { form: "days present", text: "1d 2h 3m 4s", seconds: 93784 },
  { form: "days, sparse", text: "2d 5m", seconds: 173100 },
  { form: "days only", text: "3d", seconds: 259200 },
  { form: "many days", text: "10d 23h 59m 59s", seconds: 950399 },
  { form: "minutes and seconds", text: "45m 12s", seconds: 2712 },
  { form: "spelled out", text: "2 hours 5 minutes", seconds: 7500 },
  { form: "spelled out with days", text: "1 day 2 hours", seconds: 93600 },
  { form: "plural days spelled out", text: "2 days 30 minutes", seconds: 174600 },
  { form: "seconds only", text: "42s", seconds: 42 },
  { form: "nothing parseable", text: "unknown", seconds: NaN }
];

test("estimated printing time: every slicer duration form, days included", async () => {
  for (const { form, text, seconds } of DURATIONS) {
    const r = await run(
      `dur-${DURATIONS.indexOf(DURATIONS.find((d) => d.form === form)!)}.gcode`,
      makeGcode({ header: [`; estimated printing time (normal mode) = ${text}`] })
    );
    if (Number.isNaN(seconds)) {
      assert.equal(r.estimatedDurationS, null, `«${text}» (${form}) must not invent a duration`);
    } else {
      assert.equal(r.estimatedDurationS, seconds, `«${text}» (${form})`);
    }
  }
});

test("a day in the estimate reaches estimatedDurationS, not just the parser", async () => {
  const r = await run(
    "multiday.gcode",
    makeGcode({ header: ["; estimated printing time (normal mode) = 1d 2h 3m 4s"] })
  );
  // 93 784 s = 26 h 3 m 4 s. Reading it as 7 384 s (2 h 3 m 4 s) is the bug: it
  // would fit a 26-hour print into an 8-hour night window.
  assert.equal(r.estimatedDurationS, 93784);
});

// ── Filament usage, per slicer dialect ───────────────────────────────────────
//
// PrusaSlicer/SuperSlicer/Orca write `key [unit] = value`; BambuStudio writes
// `total filament weight [g] : value` — a different noun AND a different
// separator. Reading only the first dialect left every BambuStudio file with no
// weight at all, which is the estimate the consumption reconciliation leans on.

const FILAMENT_FORMS: { slicer: string; lines: string[]; g: number | null; mm: number | null }[] = [
  {
    slicer: "PrusaSlicer",
    lines: ["; filament used [mm] = 8763.13", "; filament used [g] = 26.15"],
    g: 26.15,
    mm: 8763.13
  },
  {
    slicer: "PrusaSlicer (total)",
    lines: ["; total filament used [mm] = 8763.13", "; total filament used [g] = 26.15"],
    g: 26.15,
    mm: 8763.13
  },
  {
    slicer: "BambuStudio",
    lines: ["; total filament weight [g] : 128.44", "; total filament length [mm] : 41234.5"],
    g: 128.44,
    mm: 41234.5
  },
  {
    slicer: "OrcaSlicer (colon form)",
    lines: ["; filament used [g] : 12.5", "; filament used [mm] : 4100"],
    g: 12.5,
    mm: 4100
  },
  {
    slicer: "Cura (metres, no bracketed unit)",
    lines: [";Filament used: 3.8073m"],
    g: null,
    mm: 3807.3
  },
  {
    slicer: "volume only — neither field may be invented",
    lines: ["; filament used [cm3] = 21.08"],
    g: null,
    mm: null
  }
];

test("filament usage is read in every slicer dialect, and only from its own unit", async () => {
  for (const form of FILAMENT_FORMS) {
    const r = await run(
      `fil-${FILAMENT_FORMS.indexOf(form)}.gcode`,
      // `header` replaces the fixture's own usage lines, so each dialect stands alone.
      makeGcode({ header: form.lines })
    );
    assert.equal(r.estimatedFilamentG, form.g, `${form.slicer}: grams`);
    assert.equal(r.data.filamentUsedMm, form.mm, `${form.slicer}: millimetres`);
  }
});

// ── Parser equivalence and cost ──────────────────────────────────────────────

test("axis values parse bit-identically to the language's own number parser", async () => {
  // The hot loop reads a decimal without materialising a string. That is only
  // safe if it is *correctly rounded*, so it is checked against Number() itself
  // over every shape a slicer emits — including the ones it must decline.
  const { readAxis } = await import("./gcode");
  const samples = [
    "0", "1", "-1", "+1", "5.", "-5.", ".5", "-.5", ".03338", "0.03338",
    "123.456", "-123.456", "0.1", "0.2", "0.3", "255.9999", "-0",
    "12345678901234", "1.2345678901234",
    // Past the exact-mantissa window: these take the string fallback, and must
    // still agree with the language.
    "123456789012345678901234.5", "0.0000000000000000001",
    "999999999999999999", "0.1234567890123456789"
  ];
  for (const sample of samples) {
    const expected = Number(sample);
    const actual = readAxis(`G1 X${sample}`, "x");
    assert.ok(Object.is(actual, expected), `X${sample}: ${actual} ≠ ${expected}`);
  }
  // Scientific notation is deliberately NOT in the grammar — no slicer emits it,
  // and the trailing junk rule applies: `X1e3` is the value 1, as it always was.
  assert.equal(readAxis("G1 X1e3", "x"), 1);
  // Random differential sweep — the exact-mantissa path must never diverge.
  let seed = 20260828;
  const rnd = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
  for (let i = 0; i < 5000; i += 1) {
    const digits = 1 + Math.floor(rnd() * 8);
    const frac = Math.floor(rnd() * 7);
    const text = `${rnd() < 0.5 ? "-" : ""}${(rnd() * 10 ** digits).toFixed(frac)}`;
    assert.equal(readAxis(`G1 Y${text}`, "y"), Number(text), `Y${text}`);
  }
});

test("an axis letter only counts at the start of a word, and the first one wins", async () => {
  const { readAxis } = await import("./gcode");
  assert.equal(readAxis("G1 X10 Y20", "x"), 10);
  assert.equal(readAxis("G1 X10 X20", "x"), 10, "first occurrence wins");
  assert.equal(readAxis("M117 MAX", "a".replace("a", "x") as "x"), null, "not an axis word");
  assert.equal(readAxis("G1 X12abc", "x"), 12, "trailing junk is ignored");
  assert.equal(readAxis("G1 Xfoo", "x"), null, "a letter is not a number");
  assert.equal(readAxis("G1 X-", "x"), null, "a bare sign is not a number");
  assert.equal(readAxis("X5", "x"), null, "the command word itself is never an axis");
  assert.equal(readAxis("G1\tX7", "x"), 7, "a tab separates words too");
});

test("CRLF, lone CR and a missing final newline all yield the same analysis", async () => {
  const lines = makeGcode().split("\n");
  const lf = lines.join("\n");
  const crlf = lines.join("\r\n");
  const cr = lines.join("\r");
  const noTrailing = lf.replace(/\n+$/, "");
  const [a, b, c, d] = await Promise.all([
    run("lf.gcode", lf),
    run("crlf.gcode", crlf),
    run("cr.gcode", cr),
    run("notrail.gcode", noTrailing)
  ]);
  for (const [name, other] of [["crlf", b], ["cr", c], ["no trailing newline", d]] as const) {
    assert.deepEqual(other.data.bbox, a.data.bbox, `${name}: bbox`);
    assert.equal(other.data.motionCommands, a.data.motionCommands, `${name}: motion commands`);
    assert.equal(other.estimatedDurationS, a.estimatedDurationS, `${name}: duration`);
  }
});

test("a chunk boundary inside a CRLF pair does not split or lose a line", async () => {
  // The reader holds a trailing \r back until the next chunk decides whether it
  // is a lone break or half a pair. Without that, a forbidden command landing on
  // the wrong side of a 1 MB boundary could be read as two half-lines.
  const filler = Array.from({ length: 200_000 }, (_, i) => `G1 X${i % 100} Y${i % 90} E.01`);
  const gcode = makeGcode({ moves: [...filler, "M502", ...filler] });
  const r = await run("boundary.gcode", gcode.replace(/\n/g, "\r\n"));
  assert.ok(
    r.blockers.some((b) => b.code === "gcode_forbidden_command" && /M502/.test(b.message)),
    "the forbidden command is still seen across the chunk boundary"
  );
});

test("a 50 MB G-code is analysed well inside the analysis budget", async (t) => {
  // The regression this pins: the parser compiled four regexes per motion command
  // and put every line through the microtask queue, so a 50 MB OrcaSlicer file
  // took ~50 s against a 30 s budget. Every large upload came back
  // `analysis: failed` for a reason that had nothing to do with the file.
  //
  // The bound is deliberately loose (CI hardware varies); the failure it catches
  // is an order-of-magnitude regression, not a few percent.
  const header = [
    "; generated by OrcaSlicer 2.3.0",
    "; printer_model = Bambu Lab A1",
    "; filament_type = PLA",
    "; printable_area = 0x0,256x0,256x256,0x256"
  ];
  const path = `${dir}/huge.gcode`;
  const out = fs.createWriteStream(path);
  out.write(`${header.join("\n")}\nG21\nG90\nM83\n`);
  const block: string[] = [];
  for (let i = 0; i < 2000; i += 1) {
    block.push(`G1 X${(60 + (i % 120)).toFixed(3)} Y${(60 + ((i * 13) % 120)).toFixed(3)} E.03338`);
  }
  const chunk = `${block.join("\n")}\n`;
  const rounds = Math.ceil((50 * 1024 * 1024) / Buffer.byteLength(chunk));
  for (let i = 0; i < rounds; i += 1) {
    if (!out.write(chunk)) await new Promise<void>((r) => out.once("drain", () => r()));
  }
  await new Promise<void>((r) => out.end(() => r()));
  const sizeMb = fs.statSync(path).size / 1048576;
  assert.ok(sizeMb >= 50, `fixture is ${sizeMb.toFixed(1)} MB`);

  const started = Date.now();
  const r = await analyzeGcode(path);
  const elapsed = Date.now() - started;
  t.diagnostic(`${sizeMb.toFixed(1)} MB analysed in ${elapsed} ms`);
  assert.equal(r.data.motionCommands, rounds * 2000);
  assert.ok(
    elapsed < 25_000,
    `analysing ${sizeMb.toFixed(1)} MB took ${elapsed} ms — the 30 s analysis budget is at risk`
  );
});
