import assert from "node:assert/strict";
import fs from "node:fs";
import { afterEach, beforeEach, test } from "node:test";

import { makeGcode, tempDir, writeFixture } from "../testkit/fixtures";
import { analyzeGcode } from "./gcode";

let dir: string;
beforeEach(() => {
  dir = tempDir();
});
afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

function run(name: string, gcode: string) {
  const { path } = writeFixture(dir, name, gcode);
  return analyzeGcode(path);
}

test("extracts slicer, material, estimates and bounding box → schedulable", async () => {
  const r = await run("part.gcode", makeGcode());
  assert.equal(r.detectedFormat, "gcode");
  assert.equal(r.material, "PLA");
  assert.equal(r.layerHeightMm, 0.2);
  assert.equal(r.nozzleDiameterMm, 0.4);
  assert.equal(r.estimatedDurationS, 1 * 3600 + 5 * 60 + 12);
  assert.equal(r.estimatedFilamentG, 12.5);
  assert.equal((r.data.slicer as string), "PrusaSlicer");
  assert.equal(r.data.printerModel, "MK4");
  const bbox = r.data.bbox as { size: number[]; confidence: string };
  assert.deepEqual(bbox.size, [50, 40, 0]);
  assert.equal(bbox.confidence, "high");
  assert.equal(r.verdict, "schedulable");
});

test("relative moves (G91) are added to the running position", async () => {
  const r = await run(
    "rel.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G92 X0 Y0 Z0", "G1 X10 Y0", "G91", "G1 X5", "G1 X-20"]
    })
  );
  const bbox = r.data.bbox as { min: number[]; max: number[] };
  // abs 10 → +5 → 15 → -20 → -5. Bounds: min x -5, max x 15.
  assert.equal(bbox.min[0], -5);
  assert.equal(bbox.max[0], 15);
});

test("G92 renames the current position (origin offset) for later absolute moves", async () => {
  const r = await run(
    "g92.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G1 X10 Y10", "G92 X0 Y0", "G1 X5 Y0"]
    })
  );
  const bbox = r.data.bbox as { max: number[] };
  // After G92 X0 at physical 10, an absolute X5 maps to physical 15.
  assert.equal(bbox.max[0], 15);
});

test("inch units (G20) are converted to millimetres with a warning", async () => {
  const r = await run(
    "inch.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G20", "G90", "G1 X1 Y0"]
    })
  );
  const bbox = r.data.bbox as { max: number[] };
  assert.ok(Math.abs(bbox.max[0] - 25.4) < 1e-6);
  assert.ok(r.warnings.some((w) => w.code === "gcode_inch_units"));
});

test("arcs lower the bbox confidence and warn", async () => {
  const r = await run(
    "arc.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G1 X0 Y0", "G2 X10 Y10 I5 J0"]
    })
  );
  const bbox = r.data.bbox as { confidence: string };
  assert.equal(bbox.confidence, "medium");
  assert.ok(r.warnings.some((w) => w.code === "gcode_arcs"));
});

test("a forbidden config-mutating command (M502) blocks the file outright", async () => {
  const r = await run(
    "risky.gcode",
    makeGcode({ moves: ["G21", "G90", "M502", "G1 X10 Y10"] })
  );
  assert.equal(r.verdict, "blocked");
  assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command" && /M502/.test(b.message)));
});

test("an attended-only command (M600) forces review, not blocked", async () => {
  const r = await run(
    "swap.gcode",
    makeGcode({ moves: ["G21", "G90", "M600", "G1 X10 Y10"] })
  );
  assert.equal(r.verdict, "review");
  assert.ok(r.warnings.some((w) => w.code === "gcode_risky_command" && /M600/.test(w.message)));
});

test("firmware/file-system commands are forbidden: M997, M30, SAVE_CONFIG", async () => {
  for (const cmd of ["M997", "M30 old.gcode", "SAVE_CONFIG"]) {
    const r = await run(
      "danger.gcode",
      makeGcode({ moves: ["G21", "G90", cmd, "G1 X10 Y10"] })
    );
    assert.equal(r.verdict, "blocked", cmd);
    assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command"), cmd);
  }
});

test("unknown slicer + unknown target → review, never auto-safe", async () => {
  const r = await run("bare.gcode", ["G21", "G90", "G1 X0 Y0", "G1 X30 Y20"].join("\n"));
  assert.equal(r.verdict, "review");
  assert.ok(r.warnings.some((w) => w.code === "gcode_unknown_slicer"));
  assert.ok(r.warnings.some((w) => w.code === "gcode_unknown_target"));
});

test("a large G-code is analysed by streaming (no whole-file load)", async () => {
  const header = ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"];
  const moves: string[] = ["G21", "G90"];
  for (let i = 0; i < 40000; i++) {
    moves.push(`G1 X${i % 200} Y${(i * 7) % 150} E${i * 0.01}`);
  }
  const r = await run("big.gcode", makeGcode({ header, moves }));
  const bbox = r.data.bbox as { max: number[] };
  assert.equal(bbox.max[0], 199);
  assert.equal(bbox.max[1], 149);
  assert.equal(r.data.motionCommands, 40000);
});
