import assert from "node:assert/strict";
import fs from "node:fs";
import { afterEach, beforeEach, test } from "node:test";

import { makeGcode, tempDir, writeFixture } from "../testkit/fixtures";
import { analyzeGcode } from "./gcode";

let dir: string;
beforeEach(() => {
  dir = tempDir();
});
afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

function run(name: string, gcode: string) {
  const { path } = writeFixture(dir, name, gcode);
  return analyzeGcode(path);
}

test("extracts slicer, material, estimates and bounding box → schedulable", async () => {
  const r = await run("part.gcode", makeGcode());
  assert.equal(r.detectedFormat, "gcode");
  assert.equal(r.material, "PLA");
  assert.equal(r.layerHeightMm, 0.2);
  assert.equal(r.nozzleDiameterMm, 0.4);
  assert.equal(r.estimatedDurationS, 1 * 3600 + 5 * 60 + 12);
  assert.equal(r.estimatedFilamentG, 12.5);
  assert.equal((r.data.slicer as string), "PrusaSlicer");
  assert.equal(r.data.printerModel, "MK4");
  const bbox = r.data.bbox as { size: number[]; confidence: string };
  assert.deepEqual(bbox.size, [50, 40, 0]);
  assert.equal(bbox.confidence, "high");
  assert.equal(r.verdict, "schedulable");
});

test("relative moves (G91) are added to the running position", async () => {
  const r = await run(
    "rel.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G92 X0 Y0 Z0", "G1 X10 Y0", "G91", "G1 X5", "G1 X-20"]
    })
  );
  const bbox = r.data.bbox as { min: number[]; max: number[] };
  // abs 10 → +5 → 15 → -20 → -5. Bounds: min x -5, max x 15.
  assert.equal(bbox.min[0], -5);
  assert.equal(bbox.max[0], 15);
});

test("G92 renames the current position (origin offset) for later absolute moves", async () => {
  const r = await run(
    "g92.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G1 X10 Y10", "G92 X0 Y0", "G1 X5 Y0"]
    })
  );
  const bbox = r.data.bbox as { max: number[] };
  // After G92 X0 at physical 10, an absolute X5 maps to physical 15.
  assert.equal(bbox.max[0], 15);
});

test("inch units (G20) are converted to millimetres with a warning", async () => {
  const r = await run(
    "inch.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G20", "G90", "G1 X1 Y0"]
    })
  );
  const bbox = r.data.bbox as { max: number[] };
  assert.ok(Math.abs(bbox.max[0] - 25.4) < 1e-6);
  assert.ok(r.warnings.some((w) => w.code === "gcode_inch_units"));
});

test("arcs lower the bbox confidence and warn", async () => {
  const r = await run(
    "arc.gcode",
    makeGcode({
      header: ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"],
      moves: ["G21", "G90", "G1 X0 Y0", "G2 X10 Y10 I5 J0"]
    })
  );
  const bbox = r.data.bbox as { confidence: string };
  assert.equal(bbox.confidence, "medium");
  assert.ok(r.warnings.some((w) => w.code === "gcode_arcs"));
});

test("a forbidden config-mutating command (M502) blocks the file outright", async () => {
  const r = await run(
    "risky.gcode",
    makeGcode({ moves: ["G21", "G90", "M502", "G1 X10 Y10"] })
  );
  assert.equal(r.verdict, "blocked");
  assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command" && /M502/.test(b.message)));
});

test("an attended-only command (M600) forces review, not blocked", async () => {
  const r = await run(
    "swap.gcode",
    makeGcode({ moves: ["G21", "G90", "M600", "G1 X10 Y10"] })
  );
  assert.equal(r.verdict, "review");
  assert.ok(r.warnings.some((w) => w.code === "gcode_risky_command" && /M600/.test(w.message)));
});

test("firmware/file-system commands are forbidden: M997, M30, SAVE_CONFIG", async () => {
  for (const cmd of ["M997", "M30 old.gcode", "SAVE_CONFIG"]) {
    const r = await run(
      "danger.gcode",
      makeGcode({ moves: ["G21", "G90", cmd, "G1 X10 Y10"] })
    );
    assert.equal(r.verdict, "blocked", cmd);
    assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command"), cmd);
  }
});

test("unknown slicer + unknown target → review, never auto-safe", async () => {
  const r = await run("bare.gcode", ["G21", "G90", "G1 X0 Y0", "G1 X30 Y20"].join("\n"));
  assert.equal(r.verdict, "review");
  assert.ok(r.warnings.some((w) => w.code === "gcode_unknown_slicer"));
  assert.ok(r.warnings.some((w) => w.code === "gcode_unknown_target"));
});

test("a large G-code is analysed by streaming (no whole-file load)", async () => {
  const header = ["; generated by PrusaSlicer 2.7.1", "; printer_model = MK4", "; filament_type = PLA"];
  const moves: string[] = ["G21", "G90"];
  for (let i = 0; i < 40000; i++) {
    moves.push(`G1 X${i % 200} Y${(i * 7) % 150} E${i * 0.01}`);
  }
  const r = await run("big.gcode", makeGcode({ header, moves }));
  const bbox = r.data.bbox as { max: number[] };
  assert.equal(bbox.max[0], 199);
  assert.equal(bbox.max[1], 149);
  assert.equal(r.data.motionCommands, 40000);
});

// ── Bambu Lab: the vendor's own start G-code, end to end ────────────────────
//
// Reproduces the shape of a real OrcaSlicer-for-A1 file: an off-bed purge line, the
// stock levelling block with its `M500`, and an object bracketed by the slicer's own
// markers. This is the file that used to come out of the pipeline `blocked`.

const A1_HEADER = [
  "; generated by OrcaSlicer 2.3.0 on 2026-08-14 at 07:11:45",
  "; printer_model = Bambu Lab A1",
  "; filament_type = PETG",
  "; layer_height = 0.2",
  "; nozzle_diameter = 0.4",
  "; printable_area = 0x0,256x0,256x256,0x256"
];

/** Machine preamble: purge line at Y-0.5 (off the bed) + the levelling block. */
const A1_PREAMBLE = [
  "G21",
  "G90",
  "M83",
  "M204 S6000",
  "G1 X108 Y-0.5 Z0.3 F30000",
  "G1 X153 Y-0.5 E4.9 F6000 ; nozzle load line, deliberately off the bed",
  "M1002 judge_flag g29_before_print_flag",
  "G29.2 S1",
  "M622 J1",
  "    M1002 gcode_claim_action : 1",
  "    G29 A1 X109.562 Y59.325 I32.975 J137.35",
  "    M400",
  "    M500 ; save cali data",
  "M623"
];

/** A 30×30 object at X110..140 / Y60..90, wrapped in the object markers. */
const A1_OBJECT = [
  "; start printing object, unique label id: 8",
  "G1 X110 Y60 Z0.2 F3000",
  "G1 X140 Y60 E1.5",
  "G1 X140 Y90 E1.5",
  "G1 X110 Y90 E1.5",
  "G1 X110 Y60 E1.5",
  "; stop printing object, unique label id: 8"
];

function a1Gcode(extra: { beforeLevelling?: string[]; inObject?: string[] } = {}) {
  return [
    ...A1_HEADER,
    ...(extra.beforeLevelling ?? []),
    ...A1_PREAMBLE,
    ...A1_OBJECT.slice(0, 1),
    ...(extra.inObject ?? []),
    ...A1_OBJECT.slice(1),
    ""
  ].join("\n");
}

test("Bambu A1: the stock levelling M500 does not block the file", async () => {
  const r = await run("a1.gcode", a1Gcode());
  assert.deepEqual(r.blockers, []);
  assert.equal(r.verdict, "schedulable");
  assert.ok(r.warnings.some((w) => w.code === "gcode_vendor_calibration_save"));
  assert.equal(r.data.printerModel, "Bambu Lab A1");
  assert.equal(r.material, "PETG");
});

test("Bambu A1: a settings mutation ahead of the levelling block still blocks", async () => {
  const r = await run("a1-tampered.gcode", a1Gcode({ beforeLevelling: ["M92 E9999"] }));
  assert.equal(r.verdict, "blocked");
  assert.ok(r.blockers.some((b) => b.code === "gcode_forbidden_command" && /M500/.test(b.message)));
});

test("bbox measures the object, not the machine's off-bed purge and parking", async () => {
  const r = await run("a1-bbox.gcode", a1Gcode());
  const bbox = r.data.bbox as { min: number[]; max: number[]; size: number[] };
  // The object only: X110..140, Y60..90. The purge line at X108..153 / Y-0.5 is
  // off the bed, and the travel to it deposits nothing.
  assert.deepEqual(bbox.min, [110, 60, 0.2]);
  assert.deepEqual(bbox.max, [140, 90, 0.2]);
  assert.deepEqual(bbox.size, [30, 30, 0]);
  assert.equal(r.data.bboxBasis, "object");
  assert.ok(r.warnings.some((w) => w.code === "gcode_purge_outside_bed"));

  // The raw toolpath is still reported beside it — nothing is hidden, only
  // attributed correctly.
  const toolpath = r.data.toolpathBbox as { min: number[]; max: number[] };
  assert.equal(toolpath.min[1], -0.5);
  assert.equal(toolpath.max[0], 153);
});

test("the mid-print filament flush is excluded from the object's box", async () => {
  // A toolchange happens *inside* the object markers and wipes at X-48.2 — the
  // reason object markers alone are not enough to bound the model.
  const r = await run(
    "a1-flush.gcode",
    a1Gcode({ inObject: ["G1 X-48.2 Y128 F18000", "G1 X-38.2 Y128 E40 ; flush", "G1 X110 Y60 F18000"] })
  );
  const bbox = r.data.bbox as { min: number[]; max: number[] };
  assert.deepEqual(bbox.min, [110, 60, 0.2]);
  assert.deepEqual(bbox.max, [140, 90, 0.2]);
});

test("Bambu pseudo-tools (T255 park, T1000 AMS unload) are not counted as extruders", async () => {
  const r = await run("a1-tools.gcode", a1Gcode({ inObject: ["T1000", "T0", "T255"] }));
  assert.equal(r.data.toolCount, 1);
});

test("a file with no object markers falls back to everything it extrudes", async () => {
  const r = await run(
    "plain.gcode",
    makeGcode({ moves: ["G21", "G90", "G1 X5 Y5 Z0.2", "G1 X60 Y45 E3", "G1 X200 Y200 F9000"] })
  );
  const bbox = r.data.bbox as { max: number[] };
  // The trailing travel to (200,200) deposits nothing, so it is not the model.
  assert.equal(r.data.bboxBasis, "extrusion");
  assert.deepEqual(bbox.max, [60, 45, 0.2]);
});

test("axis values without a leading zero are read (OrcaSlicer writes E.03338, Z.3)", async () => {
  // Not a corner case: OrcaSlicer omits the leading zero on fractions, so 94 731 of
  // the 96 480 E words in a real A1 file take this form. A pattern that demands a
  // digit before the point sees ~2 % of the extrusion and measures the model from
  // that sample.
  const r = await run(
    "leading-dot.gcode",
    [
      "; generated by OrcaSlicer 2.3.0",
      "; printer_model = Bambu Lab A1",
      "; filament_type = PETG",
      "; printable_area = 0x0,256x0,256x256,0x256",
      "G21",
      "G90",
      "M83",
      "G1 X100 Y100 Z.3 F3000",
      "G1 X130.307 Y153.795 E.0004",
      "G1 X129.752 Y154.476 E.03338",
      "G1 X.5 Y.25 E.5",
      "G1 X-.5 Y-.25 E.5",
      ""
    ].join("\n")
  );
  const bbox = r.data.bbox as { min: number[]; max: number[] };
  // The model's box: `Z.3` is read as the layer height, and the extruded extremes
  // bound it. The `X-.5 Y-.25` move is off the declared bed, so it is correctly
  // *not* part of the model…
  assert.deepEqual(bbox.min, [0.5, 0.25, 0.3]);
  assert.deepEqual(bbox.max, [130.307, 154.476, 0.3]);
  // …but it was still parsed, which the unfiltered toolpath box shows.
  const toolpath = r.data.toolpathBbox as { min: number[] };
  assert.deepEqual(toolpath.min, [-0.5, -0.25, 0.3], "negative leading-dot values are read");
});

test("a trailing-point value (X5.) is read rather than dropped", async () => {
  const r = await run(
    "trailing-dot.gcode",
    makeGcode({ moves: ["G21", "G90", "G1 X0 Y0 Z0.2", "G1 X5. Y7. E1"] })
  );
  const bbox = r.data.bbox as { max: number[] };
  assert.deepEqual(bbox.max.slice(0, 2), [5, 7]);
});
