import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, test } from "node:test";

import { analyzeInWorker } from "./workerHost";
import type { AnalyzerInput, AnalyzerLimits } from "./index";

/*
 * The analyzer runs in a worker thread so a timeout can genuinely TERMINATE it —
 * even a synchronous, event-loop-blocking parse — rather than merely rejecting an
 * outer Promise while the work keeps running. This is what makes `concurrency: 1`
 * mean at most one analyzer actually executing.
 */

const LIMITS: AnalyzerLimits = {
  zipMaxEntries: 100,
  zipMaxEntryBytes: 1 << 20,
  zipMaxTotalBytes: 1 << 20,
  zipMaxRatio: 200,
  xmlMaxBytes: 1 << 20
};

const cleanups: Array<() => void> = [];
afterEach(() => {
  for (const c of cleanups.splice(0)) c();
});

function tempFile(name: string, content: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "atelier-wh-"));
  cleanups.push(() => fs.rmSync(dir, { recursive: true, force: true }));
  const p = path.join(dir, name);
  fs.writeFileSync(p, content);
  return p;
}

function input(filePath: string): AnalyzerInput {
  return { path: filePath, sizeBytes: fs.statSync(filePath).size, fileName: path.basename(filePath) };
}

test("the real analyzer runs in a worker and returns a result off the main thread", async () => {
  const gcode = [
    "; generated by PrusaSlicer 2.7.1",
    "; printer_model = MK4",
    "; filament_type = PLA",
    "G21",
    "G90",
    "G1 X0 Y0",
    "G1 X40 Y30"
  ].join("\n");
  const analyze = analyzeInWorker(5000);
  const result = await analyze(input(tempFile("part.gcode", gcode)), LIMITS);
  assert.equal(result.detectedFormat, "gcode");
  assert.equal(result.material, "PLA");
});

test("a timeout TERMINATES a synchronously-blocking worker (does not just reject and leak it)", async () => {
  // A worker that spins forever synchronously — a Promise.race timeout on the
  // main thread could never stop it; only worker.terminate() can.
  const hang = tempFile(
    "hang.ts",
    `import { parentPort } from "node:worker_threads";\nvoid parentPort;\nfor (;;) { /* block forever */ }\n`
  );
  const analyze = analyzeInWorker(300, { workerPath: hang, execArgv: ["--import", "tsx"] });

  const started = Date.now();
  await assert.rejects(
    analyze(input(tempFile("m.stl", "x")), LIMITS),
    (e: unknown) => e instanceof Error && /превысил лимит/.test(e.message)
  );
  const elapsed = Date.now() - started;
  // If termination worked, this resolved near the 300 ms budget, not never. The
  // test process also exits promptly — a non-terminated spinning worker would
  // otherwise keep the thread pool busy.
  assert.ok(elapsed < 4000, `timed out and terminated promptly (took ${elapsed} ms)`);
});

test("a worker that crashes is reported as a rejection, not a hang", async () => {
  const crash = tempFile(
    "crash.ts",
    `throw new Error("boom");\n`
  );
  const analyze = analyzeInWorker(5000, { workerPath: crash, execArgv: ["--import", "tsx"] });
  await assert.rejects(analyze(input(tempFile("m.stl", "x")), LIMITS));
});
