import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";

const crc32 = zlib.crc32;

// ── Temp-file helpers ────────────────────────────────────────────────────────

/** A fresh temp directory for a test (caller removes it in afterEach). */
export function tempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "atelier-analyze-"));
}

/** Writes a fixture into `dir` and returns its path + byte size. */
export function writeFixture(dir: string, name: string, data: Buffer | string): { path: string; size: number } {
  const buf = typeof data === "string" ? Buffer.from(data, "utf8") : data;
  const p = path.join(dir, name);
  fs.writeFileSync(p, buf);
  return { path: p, size: buf.length };
}

/**
 * Tiny in-memory fixtures for the analyzer/upload tests: builders for binary and
 * ASCII STL, G-code, and — crucially — a small hand-rolled ZIP writer that can
 * *lie* about entry sizes, names, unix modes and compression, so the ZIP-bomb /
 * traversal / symlink guards can be exercised with fixtures a few bytes long.
 *
 * Kept out of the production build (see tsconfig.build.json `testkit` exclude)
 * and out of the test glob (not a `*.test.ts` file), but still type-checked.
 */

// ── STL ──────────────────────────────────────────────────────────────────────

export interface StlTriangle {
  vertices: [number, number, number][]; // three [x,y,z]
}

/** A valid binary STL over the given triangles (80-byte header + count + records). */
export function makeBinaryStl(triangles: StlTriangle[]): Buffer {
  const header = Buffer.alloc(80);
  const count = Buffer.alloc(4);
  count.writeUInt32LE(triangles.length, 0);
  const body = Buffer.concat(
    triangles.map((t) => {
      const rec = Buffer.alloc(50);
      // normal left as 0; write the 3 vertices at offset 12.
      let o = 12;
      for (const v of t.vertices) {
        rec.writeFloatLE(v[0], o);
        rec.writeFloatLE(v[1], o + 4);
        rec.writeFloatLE(v[2], o + 8);
        o += 12;
      }
      return rec;
    })
  );
  return Buffer.concat([header, count, body]);
}

/** A cube's worth of binary-STL triangles roughly spanning [0..size]³ (2 tris). */
export function unitCubeTriangles(size = 20): StlTriangle[] {
  return [
    { vertices: [[0, 0, 0], [size, 0, 0], [size, size, 0]] },
    { vertices: [[0, 0, 0], [size, size, size], [0, size, size]] }
  ];
}

export function makeAsciiStl(triangles: StlTriangle[], name = "fixture"): string {
  const facets = triangles
    .map(
      (t) => `  facet normal 0 0 0
    outer loop
${t.vertices.map((v) => `      vertex ${v[0]} ${v[1]} ${v[2]}`).join("\n")}
    endloop
  endfacet`
    )
    .join("\n");
  return `solid ${name}\n${facets}\nendsolid ${name}\n`;
}

// ── G-code ───────────────────────────────────────────────────────────────────

export interface GcodeOptions {
  header?: string[];
  moves?: string[];
}

/** Assembles a G-code string from comment header lines + motion lines. */
export function makeGcode(options: GcodeOptions = {}): string {
  const header = options.header ?? [
    "; generated by PrusaSlicer 2.7.1",
    "; printer_model = MK4",
    "; filament_type = PLA",
    "; layer_height = 0.2",
    "; nozzle_diameter = 0.4",
    "; estimated printing time (normal mode) = 1h 5m 12s",
    "; filament used [g] = 12.5"
  ];
  const moves = options.moves ?? ["G21", "G90", "G28", "G1 X0 Y0 Z0.2 F1200", "G1 X50 Y40 E5", "G1 X10 Y10"];
  return [...header, ...moves, ""].join("\n");
}

// ── ZIP writer (deliberately abusable) ───────────────────────────────────────

export interface ZipInput {
  name: string;
  data?: Buffer | string;
  /** `store` (default) or `deflate`. */
  method?: "store" | "deflate";
  /** Overrides the declared uncompressed size in headers (for bomb tests). */
  uncompressedSizeOverride?: number;
  /** Unix mode placed in the external attributes (0o120000 = symlink). */
  unixMode?: number;
  /** Marks the entry as a directory (name gets a trailing slash, empty data). */
  directory?: boolean;
}

const SIG_LOCAL = 0x04034b50;
const SIG_CENTRAL = 0x02014b50;
const SIG_EOCD = 0x06054b50;
const SIG_ZIP64_EOCD = 0x06064b50;
const SIG_ZIP64_LOCATOR = 0x07064b50;
const SENTINEL = 0xffffffff;

export interface ZipOptions {
  /**
   * Emit ZIP64 structures. `"full"` reproduces exactly what miniz — the writer
   * inside PrusaSlicer / OrcaSlicer / BambuStudio — puts in an ordinary `.3mf`:
   * every central-directory record sentinelled with a 24-byte ZIP64 extra field,
   * a ZIP64 end-of-central-directory record and its locator, and a classic EOCD
   * whose directory offset is `0xFFFFFFFF`. `"eocd"` sentinels only the EOCD
   * (entries keep their 32-bit fields), which other writers do.
   */
  zip64?: "full" | "eocd";
  /** Trailing archive comment — exercises the EOCD tail scan. */
  comment?: string;
  /** Drops the ZIP64 records while keeping the sentinels (a corrupt archive). */
  omitZip64Record?: boolean;
}

/** Builds a ZIP archive. Fields can be spoofed so security guards can be tested. */
export function makeZip(entries: ZipInput[], options: ZipOptions = {}): Buffer {
  const zip64 = options.zip64;
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;

  for (const entry of entries) {
    const name = entry.directory && !entry.name.endsWith("/") ? `${entry.name}/` : entry.name;
    const rawData = entry.directory ? Buffer.alloc(0) : toBuffer(entry.data ?? Buffer.alloc(0));
    const method = entry.method === "deflate" ? 8 : 0;
    const stored = method === 8 ? zlib.deflateRawSync(rawData) : rawData;
    const crc = crc32(rawData) >>> 0;
    const uncompressed = entry.uncompressedSizeOverride ?? rawData.length;
    const nameBuf = Buffer.from(name, "utf8");

    const local = Buffer.alloc(30);
    local.writeUInt32LE(SIG_LOCAL, 0);
    local.writeUInt16LE(20, 4); // version needed
    local.writeUInt16LE(0, 6); // flags
    local.writeUInt16LE(method, 8);
    local.writeUInt16LE(0, 10); // time
    local.writeUInt16LE(0, 12); // date
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(stored.length, 18);
    local.writeUInt32LE(uncompressed, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28); // extra len
    const localRecord = Buffer.concat([local, nameBuf, stored]);
    locals.push(localRecord);

    // ZIP64 "full": the fixed record carries sentinels and the real 64-bit
    // values live in the extra field, in the APPNOTE order uncompressed →
    // compressed → local-header offset.
    const wide = zip64 === "full";
    const extra = wide ? Buffer.alloc(28) : Buffer.alloc(0);
    if (wide) {
      extra.writeUInt16LE(0x0001, 0);
      extra.writeUInt16LE(24, 2);
      extra.writeBigUInt64LE(BigInt(uncompressed), 4);
      extra.writeBigUInt64LE(BigInt(stored.length), 12);
      extra.writeBigUInt64LE(BigInt(offset), 20);
    }

    const central = Buffer.alloc(46);
    central.writeUInt32LE(SIG_CENTRAL, 0);
    central.writeUInt16LE(wide ? 45 : 20, 4); // version made by
    central.writeUInt16LE(wide ? 45 : 20, 6); // version needed
    central.writeUInt16LE(0, 8); // flags
    central.writeUInt16LE(method, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(0, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(wide ? SENTINEL : stored.length, 20);
    central.writeUInt32LE(wide ? SENTINEL : uncompressed, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt16LE(extra.length, 30);
    central.writeUInt16LE(0, 32); // comment
    central.writeUInt16LE(0, 34); // disk
    central.writeUInt16LE(0, 36); // internal attrs
    const externalAttrs = entry.unixMode !== undefined ? (entry.unixMode << 16) >>> 0 : 0;
    central.writeUInt32LE(externalAttrs, 38);
    central.writeUInt32LE(wide ? SENTINEL : offset, 42);
    centrals.push(Buffer.concat([central, nameBuf, extra]));

    offset += localRecord.length;
  }

  const centralDir = Buffer.concat(centrals);
  const localSection = Buffer.concat(locals);
  const cdOffset = localSection.length;
  const commentBuf = Buffer.from(options.comment ?? "", "utf8");

  const tail: Buffer[] = [];
  if (zip64 && !options.omitZip64Record) {
    const record = Buffer.alloc(56);
    record.writeUInt32LE(SIG_ZIP64_EOCD, 0);
    record.writeBigUInt64LE(BigInt(44), 4); // size of the remainder of this record
    record.writeUInt16LE(45, 12); // version made by
    record.writeUInt16LE(45, 14); // version needed
    record.writeUInt32LE(0, 16); // this disk
    record.writeUInt32LE(0, 20); // disk with the CD start
    record.writeBigUInt64LE(BigInt(entries.length), 24);
    record.writeBigUInt64LE(BigInt(entries.length), 32);
    record.writeBigUInt64LE(BigInt(centralDir.length), 40);
    record.writeBigUInt64LE(BigInt(cdOffset), 48);

    const locator = Buffer.alloc(20);
    locator.writeUInt32LE(SIG_ZIP64_LOCATOR, 0);
    locator.writeUInt32LE(0, 4); // disk holding the ZIP64 EOCD
    locator.writeBigUInt64LE(BigInt(cdOffset + centralDir.length), 8);
    locator.writeUInt32LE(1, 16); // total disks
    tail.push(record, locator);
  }

  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(SIG_EOCD, 0);
  eocd.writeUInt16LE(0, 4); // disk
  eocd.writeUInt16LE(0, 6);
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(centralDir.length, 12);
  // miniz leaves the size intact and sentinels only the offset — reproduce that.
  eocd.writeUInt32LE(zip64 ? SENTINEL : cdOffset, 16);
  eocd.writeUInt16LE(commentBuf.length, 20);

  return Buffer.concat([localSection, centralDir, ...tail, eocd, commentBuf]);
}

// ── 3MF ──────────────────────────────────────────────────────────────────────

const CONTENT_TYPES_XML =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
  '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
  '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>' +
  "</Types>";

const RELS_XML =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
  '<Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>' +
  "</Relationships>";

/** A minimal but valid `3dmodel.model` XML: one object mesh, one build item. */
export function make3mfModelXml(options: { unit?: string; size?: number; transform?: string } = {}): string {
  const s = options.size ?? 10;
  return make3mfModel({
    unit: options.unit ?? "millimeter",
    objects: [{ id: "1", vertices: [[0, 0, 0], [s, 0, 0], [s, s, s]] }],
    items: [{ objectid: "1", transform: options.transform }]
  });
}

export type Vertex = [number, number, number];

export interface ThreeMfObject {
  id: string;
  /** Mesh vertices; omit for a pure component-assembly object. */
  vertices?: (Vertex | [unknown, unknown, unknown])[];
  /** Nested component references, each with its own optional transform. */
  components?: { objectid: string; transform?: string; path?: string }[];
}

export interface ThreeMfItem {
  objectid: string;
  transform?: string;
  /** `p:path` — the production extension's "this object lives in another part". */
  path?: string;
}

/**
 * A `3dmodel.model` with arbitrary objects, components, transforms and build
 * items — the knobs the geometry tests need (units, multi-object scenes,
 * component assemblies, corrupt coordinates). `unit: null` omits the attribute
 * entirely, which is how the spec's millimetre default gets exercised.
 */
export function make3mfModel(options: {
  unit?: string | null;
  objects: ThreeMfObject[];
  items: ThreeMfItem[];
  /** Value of the `Application` metadata — how a writer names itself. */
  application?: string;
}): string {
  const unitAttr = options.unit === null || options.unit === undefined ? "" : ` unit="${options.unit}"`;
  const objects = options.objects
    .map((o) => {
      const vertices = (o.vertices ?? [])
        .map((v) => `<vertex x="${v[0]}" y="${v[1]}" z="${v[2]}"/>`)
        .join("");
      const mesh = o.vertices
        ? `<mesh><vertices>${vertices}</vertices>` +
          '<triangles><triangle v1="0" v2="1" v3="2"/></triangles></mesh>'
        : "";
      const components = o.components
        ? `<components>${o.components
            .map(
              (c) =>
                `<component${c.path === undefined ? "" : ` p:path="${c.path}"`} objectid="${c.objectid}"` +
                `${c.transform === undefined ? "" : ` transform="${c.transform}"`}/>`
            )
            .join("")}</components>`
        : "";
      return `<object id="${o.id}" type="model">${mesh}${components}</object>`;
    })
    .join("");
  const items = options.items
    .map(
      (i) =>
        `<item objectid="${i.objectid}"${i.path === undefined ? "" : ` p:path="${i.path}"`}` +
        `${i.transform === undefined ? "" : ` transform="${i.transform}"`}/>`
    )
    .join("");
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    `<model${unitAttr} xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"` +
    ' xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06">' +
    `<metadata name="Application">${options.application ?? "FixtureSlicer 1.0"}</metadata>` +
    `<resources>${objects}</resources>` +
    `<build>${items}</build>` +
    "</model>"
  );
}

/** The 8 corners of an axis-aligned box from the origin — a bbox-realistic mesh. */
export function boxVertices(sx: number, sy = sx, sz = sx, origin: Vertex = [0, 0, 0]): Vertex[] {
  const [ox, oy, oz] = origin;
  const out: Vertex[] = [];
  for (const x of [ox, ox + sx]) for (const y of [oy, oy + sy]) for (const z of [oz, oz + sz]) out.push([x, y, z]);
  return out;
}

/**
 * An OrcaSlicer-style `Metadata/model_settings.config` mapping plates to the
 * build items they hold — what makes a multi-plate project's plates attributable.
 */
export function makeModelSettingsConfig(plates: { index: number; objectIds: string[] }[]): string {
  const body = plates
    .map(
      (p) =>
        `<plate><metadata key="plater_id" value="${p.index}"/>` +
        p.objectIds
          .map(
            (id) =>
              `<model_instance><metadata key="object_id" value="${id}"/>` +
              '<metadata key="instance_id" value="0"/></model_instance>'
          )
          .join("") +
        "</plate>"
    )
    .join("");
  return `<?xml version="1.0"?><config>${body}</config>`;
}

/** A 3MF package from a model XML plus any extra entries (configs, plate assets). */
export function make3mfPackage(
  modelXml: string,
  extra: ZipInput[] = [],
  options: ZipOptions = {}
): Buffer {
  return makeZip(
    [
      { name: "[Content_Types].xml", data: CONTENT_TYPES_XML },
      { name: "_rels/.rels", data: RELS_XML },
      { name: "3D/3dmodel.model", data: modelXml },
      ...extra
    ],
    options
  );
}

/** A generic (un-sliced) 3MF package as ZIP bytes. */
export function makeGeneric3mf(modelXml = make3mfModelXml(), options: ZipOptions = {}): Buffer {
  return makeZip(
    [
      { name: "[Content_Types].xml", data: CONTENT_TYPES_XML },
      { name: "_rels/.rels", data: RELS_XML },
      { name: "3D/3dmodel.model", data: modelXml }
    ],
    options
  );
}

/**
 * A slicer *project* 3MF (model + settings, no G-code), in the layout of the
 * named tool. `application` goes into the model's `Application` metadata exactly
 * as the real writers spell it.
 */
export function makeProject3mf(
  slicer: "orca" | "bambu" | "prusa",
  options: ZipOptions = {}
): Buffer {
  const application = {
    orca: "OrcaSlicer-2.1.1",
    bambu: "BambuStudio-01.09.00.60",
    prusa: "PrusaSlicer-2.7.1"
  }[slicer];
  const modelXml = make3mfModel({
    unit: "millimeter",
    application,
    objects: [{ id: "1", vertices: boxVertices(20) }],
    items: [{ objectid: "1" }]
  });
  const extra: ZipInput[] =
    slicer === "prusa"
      ? [
          { name: "Metadata/Slic3r_PE.config", data: "; layer_height = 0.2\n" },
          { name: "Metadata/Slic3r_PE_model.config", data: "<config/>" }
        ]
      : [
          { name: "Metadata/project_settings.config", data: '{"layer_height":"0.2"}' },
          { name: "Metadata/model_settings.config", data: "<config/>" },
          { name: "Metadata/plate_1.png", data: Buffer.from([0x89, 0x50, 0x4e, 0x47]) }
        ];
  return make3mfPackage(modelXml, extra, options);
}

/** A "sliced" 3MF: generic package plus an OrcaSlicer-style G-code + config payload. */
export function makeSliced3mf(): Buffer {
  const sliceInfo =
    '<?xml version="1.0"?><config><plate>' +
    '<metadata key="printer_model_id" value="Bambu Lab X1"/>' +
    '<metadata key="filament_type" value="PLA"/>' +
    "</plate></config>";
  return makeZip([
    { name: "[Content_Types].xml", data: CONTENT_TYPES_XML },
    { name: "_rels/.rels", data: RELS_XML },
    { name: "3D/3dmodel.model", data: make3mfModelXml() },
    { name: "Metadata/slice_info.config", data: sliceInfo },
    { name: "Metadata/plate_1.gcode", data: makeGcode() },
    { name: "Metadata/plate_1.png", data: Buffer.from([0x89, 0x50, 0x4e, 0x47]) }
  ]);
}

function toBuffer(data: Buffer | string): Buffer {
  return typeof data === "string" ? Buffer.from(data, "utf8") : data;
}
