import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";

const crc32 = zlib.crc32;

// ── Temp-file helpers ────────────────────────────────────────────────────────

/** A fresh temp directory for a test (caller removes it in afterEach). */
export function tempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "atelier-analyze-"));
}

/** Writes a fixture into `dir` and returns its path + byte size. */
export function writeFixture(dir: string, name: string, data: Buffer | string): { path: string; size: number } {
  const buf = typeof data === "string" ? Buffer.from(data, "utf8") : data;
  const p = path.join(dir, name);
  fs.writeFileSync(p, buf);
  return { path: p, size: buf.length };
}

/**
 * Tiny in-memory fixtures for the analyzer/upload tests: builders for binary and
 * ASCII STL, G-code, and — crucially — a small hand-rolled ZIP writer that can
 * *lie* about entry sizes, names, unix modes and compression, so the ZIP-bomb /
 * traversal / symlink guards can be exercised with fixtures a few bytes long.
 *
 * Kept out of the production build (see tsconfig.build.json `testkit` exclude)
 * and out of the test glob (not a `*.test.ts` file), but still type-checked.
 */

// ── STL ──────────────────────────────────────────────────────────────────────

export interface StlTriangle {
  vertices: [number, number, number][]; // three [x,y,z]
}

/** A valid binary STL over the given triangles (80-byte header + count + records). */
export function makeBinaryStl(triangles: StlTriangle[]): Buffer {
  const header = Buffer.alloc(80);
  const count = Buffer.alloc(4);
  count.writeUInt32LE(triangles.length, 0);
  const body = Buffer.concat(
    triangles.map((t) => {
      const rec = Buffer.alloc(50);
      // normal left as 0; write the 3 vertices at offset 12.
      let o = 12;
      for (const v of t.vertices) {
        rec.writeFloatLE(v[0], o);
        rec.writeFloatLE(v[1], o + 4);
        rec.writeFloatLE(v[2], o + 8);
        o += 12;
      }
      return rec;
    })
  );
  return Buffer.concat([header, count, body]);
}

/** A cube's worth of binary-STL triangles roughly spanning [0..size]³ (2 tris). */
export function unitCubeTriangles(size = 20): StlTriangle[] {
  return [
    { vertices: [[0, 0, 0], [size, 0, 0], [size, size, 0]] },
    { vertices: [[0, 0, 0], [size, size, size], [0, size, size]] }
  ];
}

export function makeAsciiStl(triangles: StlTriangle[], name = "fixture"): string {
  const facets = triangles
    .map(
      (t) => `  facet normal 0 0 0
    outer loop
${t.vertices.map((v) => `      vertex ${v[0]} ${v[1]} ${v[2]}`).join("\n")}
    endloop
  endfacet`
    )
    .join("\n");
  return `solid ${name}\n${facets}\nendsolid ${name}\n`;
}

// ── G-code ───────────────────────────────────────────────────────────────────

export interface GcodeOptions {
  header?: string[];
  moves?: string[];
}

/** Assembles a G-code string from comment header lines + motion lines. */
export function makeGcode(options: GcodeOptions = {}): string {
  const header = options.header ?? [
    "; generated by PrusaSlicer 2.7.1",
    "; printer_model = MK4",
    "; filament_type = PLA",
    "; layer_height = 0.2",
    "; nozzle_diameter = 0.4",
    "; estimated printing time (normal mode) = 1h 5m 12s",
    "; filament used [g] = 12.5"
  ];
  const moves = options.moves ?? ["G21", "G90", "G28", "G1 X0 Y0 Z0.2 F1200", "G1 X50 Y40 E5", "G1 X10 Y10"];
  return [...header, ...moves, ""].join("\n");
}

// ── ZIP writer (deliberately abusable) ───────────────────────────────────────

export interface ZipInput {
  name: string;
  data?: Buffer | string;
  /** `store` (default) or `deflate`. */
  method?: "store" | "deflate";
  /** Overrides the declared uncompressed size in headers (for bomb tests). */
  uncompressedSizeOverride?: number;
  /** Unix mode placed in the external attributes (0o120000 = symlink). */
  unixMode?: number;
  /** Marks the entry as a directory (name gets a trailing slash, empty data). */
  directory?: boolean;
}

const SIG_LOCAL = 0x04034b50;
const SIG_CENTRAL = 0x02014b50;
const SIG_EOCD = 0x06054b50;

/** Builds a ZIP archive. Fields can be spoofed so security guards can be tested. */
export function makeZip(entries: ZipInput[]): Buffer {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;

  for (const entry of entries) {
    const name = entry.directory && !entry.name.endsWith("/") ? `${entry.name}/` : entry.name;
    const rawData = entry.directory ? Buffer.alloc(0) : toBuffer(entry.data ?? Buffer.alloc(0));
    const method = entry.method === "deflate" ? 8 : 0;
    const stored = method === 8 ? zlib.deflateRawSync(rawData) : rawData;
    const crc = crc32(rawData) >>> 0;
    const uncompressed = entry.uncompressedSizeOverride ?? rawData.length;
    const nameBuf = Buffer.from(name, "utf8");

    const local = Buffer.alloc(30);
    local.writeUInt32LE(SIG_LOCAL, 0);
    local.writeUInt16LE(20, 4); // version needed
    local.writeUInt16LE(0, 6); // flags
    local.writeUInt16LE(method, 8);
    local.writeUInt16LE(0, 10); // time
    local.writeUInt16LE(0, 12); // date
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(stored.length, 18);
    local.writeUInt32LE(uncompressed, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28); // extra len
    const localRecord = Buffer.concat([local, nameBuf, stored]);
    locals.push(localRecord);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(SIG_CENTRAL, 0);
    central.writeUInt16LE(20, 4); // version made by
    central.writeUInt16LE(20, 6); // version needed
    central.writeUInt16LE(0, 8); // flags
    central.writeUInt16LE(method, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(0, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(stored.length, 20);
    central.writeUInt32LE(uncompressed, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt16LE(0, 30); // extra
    central.writeUInt16LE(0, 32); // comment
    central.writeUInt16LE(0, 34); // disk
    central.writeUInt16LE(0, 36); // internal attrs
    const externalAttrs = entry.unixMode !== undefined ? (entry.unixMode << 16) >>> 0 : 0;
    central.writeUInt32LE(externalAttrs, 38);
    central.writeUInt32LE(offset, 42);
    centrals.push(Buffer.concat([central, nameBuf]));

    offset += localRecord.length;
  }

  const centralDir = Buffer.concat(centrals);
  const localSection = Buffer.concat(locals);

  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(SIG_EOCD, 0);
  eocd.writeUInt16LE(0, 4); // disk
  eocd.writeUInt16LE(0, 6);
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(centralDir.length, 12);
  eocd.writeUInt32LE(localSection.length, 16); // central dir offset = end of locals
  eocd.writeUInt16LE(0, 20); // comment len

  return Buffer.concat([localSection, centralDir, eocd]);
}

// ── 3MF ──────────────────────────────────────────────────────────────────────

const CONTENT_TYPES_XML =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
  '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
  '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>' +
  "</Types>";

const RELS_XML =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
  '<Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>' +
  "</Relationships>";

/** A minimal but valid `3dmodel.model` XML: one object mesh, one build item. */
export function make3mfModelXml(options: { unit?: string; size?: number; transform?: string } = {}): string {
  const unit = options.unit ?? "millimeter";
  const s = options.size ?? 10;
  const transform = options.transform ? ` transform="${options.transform}"` : "";
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    `<model unit="${unit}" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">` +
    "<metadata name=\"Application\">FixtureSlicer 1.0</metadata>" +
    "<resources><object id=\"1\" type=\"model\"><mesh><vertices>" +
    `<vertex x="0" y="0" z="0"/><vertex x="${s}" y="0" z="0"/><vertex x="${s}" y="${s}" z="${s}"/>` +
    "</vertices><triangles><triangle v1=\"0\" v2=\"1\" v3=\"2\"/></triangles></mesh></object></resources>" +
    `<build><item objectid="1"${transform}/></build>` +
    "</model>"
  );
}

/** A generic (un-sliced) 3MF package as ZIP bytes. */
export function makeGeneric3mf(modelXml = make3mfModelXml()): Buffer {
  return makeZip([
    { name: "[Content_Types].xml", data: CONTENT_TYPES_XML },
    { name: "_rels/.rels", data: RELS_XML },
    { name: "3D/3dmodel.model", data: modelXml }
  ]);
}

/** A "sliced" 3MF: generic package plus an OrcaSlicer-style G-code + config payload. */
export function makeSliced3mf(): Buffer {
  const sliceInfo =
    '<?xml version="1.0"?><config><plate>' +
    '<metadata key="printer_model_id" value="Bambu Lab X1"/>' +
    '<metadata key="filament_type" value="PLA"/>' +
    "</plate></config>";
  return makeZip([
    { name: "[Content_Types].xml", data: CONTENT_TYPES_XML },
    { name: "_rels/.rels", data: RELS_XML },
    { name: "3D/3dmodel.model", data: make3mfModelXml() },
    { name: "Metadata/slice_info.config", data: sliceInfo },
    { name: "Metadata/plate_1.gcode", data: makeGcode() },
    { name: "Metadata/plate_1.png", data: Buffer.from([0x89, 0x50, 0x4e, 0x47]) }
  ]);
}

function toBuffer(data: Buffer | string): Buffer {
  return typeof data === "string" ? Buffer.from(data, "utf8") : data;
}
