import fsp from "node:fs/promises";

import {
  SliceProcessError,
  SliceRuntimeUnavailableError,
  SliceTimeoutError,
  type OrcaRuntimeStatus,
  type SliceRequest,
  type SliceRunner,
  type SliceRunOutput
} from "../../../infra/slicing/sliceRunner";

/**
 * An in-process {@link SliceRunner} for tests — the "fake Orca runner" the brief
 * calls for. It performs no real slicing: on success it writes a small but
 * realistic OrcaSlicer-style G-code (with the time/filament/geometry header the
 * existing G-code analyzer parses) to the requested output path, so the slice
 * pipeline produces a genuine output artifact whose re-analysis yields real
 * estimates — without pretending those estimates came from a slicer that isn't
 * installed. Its `behavior` switch drives the timeout / unavailable / failure paths.
 */

/** A minimal OrcaSlicer-style G-code: the header carries ETA, usage and geometry. */
export const FAKE_ORCA_GCODE = [
  "; generated by OrcaSlicer 2.3.0 on 2026-07-17 at 00:00:00",
  "; printer_model = Bambu Lab A1",
  "; nozzle_diameter = 0.4",
  "; layer_height = 0.2",
  "; filament_type = PETG",
  "; estimated printing time (normal mode) = 1h 23m 45s",
  "; total filament used [mm] = 3456.7",
  "; total filament used [g] = 10.3",
  "G21",
  "G90",
  "G28",
  "G1 Z0.2 F600",
  "G1 X20 Y20 E1 F1800",
  "G1 X120 Y20 E5",
  "G1 X120 Y120 E5",
  "G1 X20 Y120 E5",
  "G1 X20 Y20 E5"
].join("\n");

export type FakeBehavior = "ok" | "timeout" | "unavailable" | "fail";

export class FakeOrcaRunner implements SliceRunner {
  readonly workerVersion: string;
  readonly pinnedVersion: string | null;
  behavior: FakeBehavior = "ok";
  sliceCount = 0;
  lastRequest: SliceRequest | null = null;
  gcode = FAKE_ORCA_GCODE;
  /** Optional hook fired mid-slice, before the output is written (to assert temp state). */
  onSlice?: (req: SliceRequest) => void | Promise<void>;

  constructor(options: { pinnedVersion?: string | null; workerVersion?: string } = {}) {
    this.pinnedVersion = options.pinnedVersion ?? "2.3.0";
    this.workerVersion = options.workerVersion ?? "orca-worker-1";
  }

  async probe(): Promise<OrcaRuntimeStatus> {
    if (this.behavior === "unavailable") {
      return {
        available: false,
        binaryPath: null,
        detectedVersion: null,
        pinnedVersion: this.pinnedVersion,
        versionMatches: null,
        networkIsolated: true,
        error: "OrcaSlicer недоступен (тестовый режим unavailable)",
        workerVersion: this.workerVersion
      };
    }
    return {
      available: true,
      binaryPath: "/fake/orca-slicer",
      detectedVersion: this.pinnedVersion,
      pinnedVersion: this.pinnedVersion,
      versionMatches: true,
      networkIsolated: true,
      error: null,
      workerVersion: this.workerVersion
    };
  }

  async slice(req: SliceRequest, options: { timeoutMs?: number; signal?: AbortSignal } = {}): Promise<SliceRunOutput> {
    this.lastRequest = req;
    if (this.behavior === "unavailable") {
      throw new SliceRuntimeUnavailableError("OrcaSlicer недоступен (тестовый режим)");
    }
    if (this.behavior === "timeout") {
      throw new SliceTimeoutError(`Превышен лимит времени слайсинга (${options.timeoutMs ?? 0} мс)`);
    }
    if (this.behavior === "fail") {
      throw new SliceProcessError("OrcaSlicer завершился с кодом 1 (тестовый режим)");
    }
    if (this.onSlice) await this.onSlice(req);
    await fsp.writeFile(req.outputPath, this.gcode, "utf8");
    this.sliceCount += 1;
    return { outputPath: req.outputPath, stdout: "sliced (fake)", stderr: "", exitCode: 0, durationMs: 3 };
  }
}
