import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { after, before, test } from "node:test";

import Fastify, { type FastifyError, type FastifyInstance } from "fastify";

/*
 * The `/api/print/artifacts` HTTP surface end-to-end: multipart uploads of all
 * three formats through the real farmStore singleton + real analyzer, the CSRF/
 * token guard, the size limit, and — crucially — proof that an upload never
 * leaks into the legacy queue or state.json.
 *
 * env freezes on first import, so process.env is set here at module top and
 * everything that reads it (farmStore, security) is imported dynamically after.
 */
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), "atelier-upload-routes-"));
const TOKEN = "upload-test-token";
process.env.ORCHESTRATOR_API_TOKEN = TOKEN;
process.env.STATE_FILE_PATH = path.join(TMP, "state.json");
process.env.MAX_UPLOAD_FILE_BYTES = "4096";
process.env.ANALYSIS_CONCURRENCY = "2";
// Isolate from the host's free disk: this suite tests upload ROUTING, not the
// disk-reserve guard (covered in artifactQuota.test.ts). Without this, a CI/dev
// disk below the production reserve would (correctly) 507 every upload here.
process.env.UPLOAD_MIN_FREE_DISK_BYTES = "1048576";
process.env.PRINTERS_CONFIG_PATH = path.join(TMP, "no-printers.json");

let app: FastifyInstance;
let farmStore: typeof import("../../app/farmStore").farmStore;

before(async () => {
  const { AppError } = await import("../../core/errors");
  const { registerSecurity } = await import("../../http/security");
  const { registerPrintQueueRoutes } = await import("./routes");
  ({ farmStore } = await import("../../app/farmStore"));

  app = Fastify();
  registerSecurity(app);
  app.setErrorHandler((error: FastifyError, _request, reply) => {
    if (error instanceof AppError) {
      reply.code(error.statusCode).send({ error: { code: error.code, message: error.message } });
      return;
    }
    const status = typeof error.statusCode === "number" ? error.statusCode : 500;
    reply.code(status).send({ error: { code: "ERR", message: error.message } });
  });
  await app.register(registerPrintQueueRoutes, {
    prefix: "/api/print",
    services: farmStore,
    commands: farmStore.commands
  });
  await app.ready();
});

after(async () => {
  await app.close();
  fs.rmSync(TMP, { recursive: true, force: true });
});

/** Builds a multipart/form-data body with one file part. */
function multipart(filename: string, data: Buffer): { payload: Buffer; headers: Record<string, string> } {
  const boundary = `----atelier${Math.random().toString(16).slice(2)}`;
  const head = Buffer.from(
    `--${boundary}\r\n` +
      `Content-Disposition: form-data; name="file"; filename="${filename}"\r\n` +
      `Content-Type: application/octet-stream\r\n\r\n`
  );
  const tail = Buffer.from(`\r\n--${boundary}--\r\n`);
  return {
    payload: Buffer.concat([head, data, tail]),
    headers: { "content-type": `multipart/form-data; boundary=${boundary}` }
  };
}

function uploadReq(filename: string, data: Buffer, extraHeaders: Record<string, string> = {}) {
  const { payload, headers } = multipart(filename, data);
  return app.inject({
    method: "POST",
    url: "/api/print/artifacts",
    payload,
    headers: { ...headers, authorization: `Bearer ${TOKEN}`, ...extraHeaders }
  });
}

// ── Fixtures (tiny, inline) ──────────────────────────────────────────────────

/** A 1-triangle binary STL; `seed` varies a coordinate so distinct seeds yield distinct content. */
function binaryStl(seed = 5): Buffer {
  const header = Buffer.alloc(84);
  header.writeUInt32LE(1, 80); // 1 triangle
  const tri = Buffer.alloc(50);
  let o = 12;
  for (const v of [[0, 0, 0], [10, 0, 0], [10, 10, seed]]) {
    tri.writeFloatLE(v[0], o);
    tri.writeFloatLE(v[1], o + 4);
    tri.writeFloatLE(v[2], o + 8);
    o += 12;
  }
  return Buffer.concat([header, tri]);
}

const GCODE = Buffer.from(
  [
    "; generated by PrusaSlicer 2.7.1",
    "; printer_model = MK4",
    "; filament_type = PLA",
    "G21",
    "G90",
    "G1 X0 Y0",
    "G1 X30 Y20"
  ].join("\n")
);

/** Waits for the analysis worker to finish, then returns the artifact detail. */
async function analyzed(artifactId: string) {
  await farmStore.artifacts.whenIdle();
  const res = await app.inject({ method: "GET", url: `/api/print/artifacts/${artifactId}` });
  assert.equal(res.statusCode, 200);
  return res.json();
}

// ── Tests ────────────────────────────────────────────────────────────────────

test("uploads a binary STL → 201, model artifact, DRAFT task, needs_preparation", async () => {
  const res = await uploadReq("cube.stl", binaryStl());
  assert.equal(res.statusCode, 201);
  const body = res.json();
  assert.equal(body.ok, true);
  assert.equal(body.blobExisted, false);
  assert.equal(body.task.state, "DRAFT");

  const detail = await analyzed(body.artifact.id);
  const latest = detail.analyses.at(-1);
  assert.equal(latest.detectedFormat, "stl");
  assert.equal(latest.state, "ready");
  assert.equal(latest.verdict, "needs_preparation");
});

test("uploads a G-code → analyzed with slicer/material metadata", async () => {
  const res = await uploadReq("part.gcode", GCODE);
  assert.equal(res.statusCode, 201);
  const detail = await analyzed(res.json().artifact.id);
  const latest = detail.analyses.at(-1);
  assert.equal(latest.detectedFormat, "gcode");
  assert.equal(latest.material, "PLA");
  assert.equal(latest.data.slicer, "PrusaSlicer");
});

test("uploads a 3MF → analyzed as a generic model (needs_preparation)", async () => {
  const { makeGeneric3mf } = await import("../../app/artifacts/testkit/fixtures");
  const res = await uploadReq("part.3mf", makeGeneric3mf());
  assert.equal(res.statusCode, 201);
  const detail = await analyzed(res.json().artifact.id);
  const latest = detail.analyses.at(-1);
  assert.equal(latest.detectedFormat, "3mf");
  assert.equal(latest.verdict, "needs_preparation");
});

test("re-uploading identical content reports blobExisted (200) and dedups the blob", async () => {
  const unique = binaryStl(42); // distinct from other tests' fixtures
  const first = await uploadReq("first.stl", unique);
  assert.equal(first.statusCode, 201);
  assert.equal(first.json().blobExisted, false);
  const again = await uploadReq("second.stl", unique);
  assert.equal(again.statusCode, 200);
  assert.equal(again.json().blobExisted, true);
});

test("a file over the size limit is refused with 413", async () => {
  const res = await uploadReq("big.gcode", Buffer.alloc(8192, 0x41));
  assert.equal(res.statusCode, 413);
  assert.equal(res.json().error.code, "PAYLOAD_TOO_LARGE");
});

test("POST /artifacts:id/analyze re-runs analysis", async () => {
  const up = await uploadReq("rerun.stl", binaryStl());
  const artifactId = up.json().artifact.id;
  await farmStore.artifacts.whenIdle();
  const res = await app.inject({
    method: "POST",
    url: `/api/print/artifacts/${artifactId}/analyze`,
    headers: { authorization: `Bearer ${TOKEN}` }
  });
  assert.equal(res.statusCode, 200);
  assert.equal(res.json().analysis.state, "pending");
});

test("the upload endpoint enforces the API token and Origin (CSRF)", async () => {
  const { payload, headers } = multipart("x.stl", binaryStl());

  // No token → 401.
  const noToken = await app.inject({ method: "POST", url: "/api/print/artifacts", payload, headers });
  assert.equal(noToken.statusCode, 401);

  // Foreign Origin even with the token → 403.
  const foreign = await app.inject({
    method: "POST",
    url: "/api/print/artifacts",
    payload,
    headers: { ...headers, authorization: `Bearer ${TOKEN}`, origin: "http://evil.example", host: "farm.local" }
  });
  assert.equal(foreign.statusCode, 403);
});

test("uploads never leak into the legacy queue or state.json", async () => {
  await uploadReq("draft.stl", binaryStl());
  await farmStore.artifacts.whenIdle();

  // The new-model open queue is empty (uploads are drafts, not queued).
  const q = await app.inject({ method: "GET", url: "/api/print/queue" });
  assert.deepEqual(q.json().queue, []);

  // The legacy in-memory queue is untouched.
  assert.deepEqual(farmStore.reads.getQueue(), []);

  // If state.json was written at all, its queue is empty.
  const stateFile = process.env.STATE_FILE_PATH as string;
  if (fs.existsSync(stateFile)) {
    const state = JSON.parse(fs.readFileSync(stateFile, "utf8"));
    assert.deepEqual(state.queue?.jobs ?? [], []);
  }

  // But the draft DOES exist in the new model's task list.
  const tasks = await app.inject({ method: "GET", url: "/api/print/tasks" });
  assert.ok(tasks.json().tasks.some((t: { state: string }) => t.state === "DRAFT"));
});
