import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { after, before, test } from "node:test";

import { OrcaCliRunner } from "./orcaCliRunner";
import { SliceRuntimeUnavailableError, SliceTimeoutError } from "./sliceRunner";

/*
 * Exercises the REAL spawn-based runner (no OrcaSlicer needed) by pointing it at
 * small Node scripts that stand in for the CLI: one that prints a version and
 * writes a plate G-code, and one that hangs so the timeout path can fire. This
 * covers probe(), version pinning, missing runtime, a successful slice, output
 * relocation, and the wall-clock kill — all through the same code that would run a
 * real binary.
 */

let TMP: string;
const NODE = process.execPath;

// A stand-in "orca": `--version` prints a banner; otherwise it writes a plate file.
const FAKE_ORCA = `
const fs = require("fs");
const path = require("path");
const args = process.argv.slice(2);
if (args.includes("--version")) { console.log("OrcaSlicer 2.3.0 (build 62)"); process.exit(0); }
const oi = args.indexOf("--outputdir");
const outdir = args[oi + 1];
fs.writeFileSync(path.join(outdir, "plate_1.gcode"), "; generated by OrcaSlicer 2.3.0\\nG1 X0 Y0\\n");
process.exit(0);
`;

// A hanging "orca" that still answers --version quickly (probe must pass first).
const SLOW_ORCA = `
const args = process.argv.slice(2);
if (args.includes("--version")) { console.log("OrcaSlicer 2.3.0"); process.exit(0); }
setTimeout(() => process.exit(0), 60000);
`;

// Like FAKE_ORCA, but records each `--version` invocation to a sidecar log so a test
// can prove how many times the runner probed for one operation.
const COUNT_ORCA = `
const fs = require("fs");
const path = require("path");
const args = process.argv.slice(2);
if (args.includes("--version")) { fs.appendFileSync(__filename + ".vlog", "v\\n"); console.log("OrcaSlicer 2.3.0 (build 62)"); process.exit(0); }
const oi = args.indexOf("--outputdir");
fs.writeFileSync(path.join(args[oi + 1], "plate_1.gcode"), "; generated by OrcaSlicer 2.3.0\\nG1 X0 Y0\\n");
process.exit(0);
`;

let fakeScript: string;
let slowScript: string;
let countScript: string;

function versionCalls(): number {
  try {
    return fs.readFileSync(`${countScript}.vlog`, "utf8").split("\n").filter(Boolean).length;
  } catch {
    return 0;
  }
}
function resetVersionCalls(): void {
  fs.rmSync(`${countScript}.vlog`, { force: true });
}

before(() => {
  TMP = fs.mkdtempSync(path.join(os.tmpdir(), "orca-cli-"));
  fakeScript = path.join(TMP, "fake-orca.js");
  slowScript = path.join(TMP, "slow-orca.js");
  countScript = path.join(TMP, "count-orca.js");
  fs.writeFileSync(fakeScript, FAKE_ORCA);
  fs.writeFileSync(slowScript, SLOW_ORCA);
  fs.writeFileSync(countScript, COUNT_ORCA);
});
after(() => {
  fs.rmSync(TMP, { recursive: true, force: true });
});

function req(workDir: string) {
  fs.mkdirSync(workDir, { recursive: true });
  const write = (name: string, body: string): string => {
    const p = path.join(workDir, name);
    fs.writeFileSync(p, body);
    return p;
  };
  return {
    modelPath: write("model.stl", "solid x"),
    machineJsonPath: write("machine.json", "{}"),
    processJsonPath: write("process.json", "{}"),
    filamentJsonPath: write("filament.json", "{}"),
    outputPath: path.join(workDir, "out.gcode"),
    workDir
  };
}

test("probe() detects the pinned version and reports available", async () => {
  const runner = new OrcaCliRunner({ command: NODE, baseArgs: [fakeScript], pinnedVersion: "2.3.0", workerVersion: "w1" });
  const status = await runner.probe();
  assert.equal(status.available, true);
  assert.equal(status.detectedVersion, "2.3.0");
  assert.equal(status.versionMatches, true);
});

test("probe() reports a version mismatch honestly (not available)", async () => {
  const runner = new OrcaCliRunner({ command: NODE, baseArgs: [fakeScript], pinnedVersion: "9.9.9", workerVersion: "w1" });
  const status = await runner.probe();
  assert.equal(status.available, false);
  assert.equal(status.versionMatches, false);
  assert.match(status.error ?? "", /9\.9\.9/);
});

test("probe() with no command configured is unavailable with a clear message", async () => {
  const runner = new OrcaCliRunner({ command: null, pinnedVersion: "2.3.0", workerVersion: "w1" });
  const status = await runner.probe();
  assert.equal(status.available, false);
  assert.match(status.error ?? "", /не настроен|ORCA_SLICER_CMD/);
});

test("probe() with a missing binary is unavailable, not a crash", async () => {
  const runner = new OrcaCliRunner({ command: path.join(TMP, "does-not-exist"), pinnedVersion: null, workerVersion: "w1" });
  const status = await runner.probe();
  assert.equal(status.available, false);
  assert.ok(status.error);
});

test("slice() runs the process and relocates the produced plate to outputPath", async () => {
  const runner = new OrcaCliRunner({ command: NODE, baseArgs: [fakeScript], pinnedVersion: "2.3.0", workerVersion: "w1" });
  const request = req(path.join(TMP, "job-ok"));
  const result = await runner.slice(request, { timeoutMs: 20000 });
  assert.equal(result.outputPath, request.outputPath);
  assert.equal(result.exitCode, 0);
  assert.ok(fs.existsSync(request.outputPath));
  assert.match(fs.readFileSync(request.outputPath, "utf8"), /OrcaSlicer/);
});

test("slice() enforces the timeout by killing the process", async () => {
  const runner = new OrcaCliRunner({ command: NODE, baseArgs: [slowScript], pinnedVersion: "2.3.0", workerVersion: "w1" });
  const request = req(path.join(TMP, "job-slow"));
  await assert.rejects(runner.slice(request, { timeoutMs: 300 }), SliceTimeoutError);
});

test("slice() throws SliceRuntimeUnavailableError when there is no runtime", async () => {
  const runner = new OrcaCliRunner({ command: null, pinnedVersion: "2.3.0", workerVersion: "w1" });
  const request = req(path.join(TMP, "job-none"));
  await assert.rejects(runner.slice(request, { timeoutMs: 1000 }), SliceRuntimeUnavailableError);
});

test("slice() reuses a supplied probe result and does NOT spawn a second --version", async () => {
  // The availability/pin gate runs once per operation: the caller probes, hands the
  // result to slice(), and slice() must not re-run `--version`.
  const runner = new OrcaCliRunner({ command: NODE, baseArgs: [countScript], pinnedVersion: "2.3.0", workerVersion: "w1" });
  resetVersionCalls();
  const probed = await runner.probe();
  assert.equal(probed.available, true);
  assert.equal(versionCalls(), 1, "the pre-flight probe is the only --version so far");

  const request = req(path.join(TMP, "job-dedup"));
  await runner.slice(request, { timeoutMs: 20000, probed });
  assert.equal(versionCalls(), 1, "slice() reused the probe — no redundant second --version");
  assert.ok(fs.existsSync(request.outputPath));
});

test("slice() WITHOUT a supplied probe result still probes itself once (guarantee intact)", async () => {
  const runner = new OrcaCliRunner({ command: NODE, baseArgs: [countScript], pinnedVersion: "2.3.0", workerVersion: "w1" });
  resetVersionCalls();
  const request = req(path.join(TMP, "job-selfprobe"));
  await runner.slice(request, { timeoutMs: 20000 });
  assert.equal(versionCalls(), 1, "a direct caller that omits `probed` is still gated by one probe");
  assert.ok(fs.existsSync(request.outputPath));
});
