import { spawn } from "node:child_process";
import fs from "node:fs";
import fsp from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { applyCliCompatShims } from "./cliCompat";

import type { StoreLogger } from "../../shared/logger";
import {
  SliceProcessError,
  SliceRuntimeUnavailableError,
  SliceTimeoutError,
  type OrcaRuntimeState,
  type OrcaRuntimeStatus,
  type OrcaSmokeResult,
  type SliceRequest,
  type SliceRunner,
  type SliceRunOptions,
  type SliceRunOutput
} from "./sliceRunner";
import { buildSmokeFixture, type SmokeFixture } from "./smokeFixture";

/**
 * The real OrcaSlicer runner: it drives the pinned OrcaSlicer CLI as a child
 * process. Every safety property the brief asks for is enforced here:
 *
 *   - **verified capability** — {@link OrcaCliRunner.verifySlicing} really slices a
 *     tiny fixture into G-code, so "available" means *can slice*, not *answered a
 *     flag*; {@link OrcaCliRunner.probe} folds that result into a staged diagnosis;
 *   - **no shell** — `spawn(bin, args, { shell: false })`, so a profile/model path
 *     can never be interpreted by a shell; arguments are passed as an array;
 *   - **timeout** — a wall-clock budget kills the process group (SIGKILL) if exceeded;
 *   - **isolated temp dir** — the slice runs in a caller-provided `workDir` (`cwd`),
 *     with a minimal environment (no inherited secrets);
 *   - **network isolation** — when configured for container mode (`command` = the
 *     container runtime, `baseArgs` carrying `--network none`), the slicer has no
 *     network; `networkIsolated` reflects that;
 *   - **honest diagnostics** — a missing runtime yields a clear message, never a
 *     fabricated slice.
 *
 * ## Two version numbers, and why `--version` is not the probe
 *
 * OrcaSlicer carries its BambuStudio ancestry in `SLIC3R_VERSION`, which is still
 * `01.10.01.50` in the 2.3.0 release (`SoftFever_VERSION`) — and that inherited
 * number is what the CLI banner prints. The CLI also has **no `--version` option at
 * all**: it answers `Invalid option --version` and exits 254, while `--help` exits 0
 * and slicing works perfectly. Treating that 254 as "binary incompatible or built
 * without CLI" (and pinning the deployment to the banner's `1.10.1`) is what made a
 * fully working OrcaSlicer 2.3.0 report itself unavailable. So: the banner is read
 * as {@link OrcaRuntimeStatus.cliBuild} only, the *release* comes from the G-code the
 * smoke slice actually produces, and capability is proven by slicing.
 *
 * Concurrency, cleanup and caching are the {@link SliceService}'s job — this class
 * runs exactly one process per call and owns none of that state.
 */

export interface OrcaCliConfig {
  /**
   * The executable to spawn. Usually the OrcaSlicer binary; in container mode this
   * is the container runtime (e.g. `docker`/`podman`) and {@link OrcaCliConfig.baseArgs}
   * carries `run --rm --network none -v … <image> orca-slicer`.
   */
  command: string | null;
  /** Arguments prepended before the slice arguments (container run/flags). Default []. */
  baseArgs?: string[];
  /** Extra arguments appended before the model path (advanced tuning). Default []. */
  extraArgs?: string[];
  /** The OrcaSlicer version this deployment pins to; null = unpinned (any version). */
  pinnedVersion: string | null;
  /** The slicing worker's own version (part of the cache key). */
  workerVersion: string;
  /** True when the configuration disables the slicer's network (container mode). */
  networkIsolated?: boolean;
  /**
   * Profile roots the smoke fixture is resolved from, most-trusted first (the
   * operator `vendor/` closure, then the mounted runtime's `resources/profiles`).
   * With none of them carrying the fixture chain, capability cannot be *proven* and
   * the probe says so instead of assuming the best.
   */
  smokeProfileRoots?: readonly string[];
  logger?: StoreLogger;
}

/** The CLI banner: `OrcaSlicer-01.10.01.50:` — the inherited BambuStudio build id. */
const BANNER_RE = /OrcaSlicer[-\s]v?(\d+(?:\.\d+){2,3})/i;
/** The G-code header the slicer stamps: `; generated by OrcaSlicer 2.3.0 on …`. */
const GCODE_VERSION_RE = /generated by\s+OrcaSlicer\s+v?(\d+\.\d+\.\d+)/i;
/** A vendor bundle's `"version": "02.03.00.03"` — tracks the OrcaSlicer release. */
const VENDOR_VERSION_RE = /"version"\s*:\s*"(\d+(?:\.\d+){2,3})"/;

/** Flags this worker actually drives the CLI with; all must exist in `--help`. */
const REQUIRED_FLAGS = ["--load-settings", "--load-filaments", "--slice", "--outputdir"] as const;

export class OrcaCliRunner implements SliceRunner {
  readonly workerVersion: string;
  readonly pinnedVersion: string | null;
  private readonly logger: StoreLogger;
  /** The last real slice check; `probe()` folds it in instead of re-slicing. */
  private smoke: OrcaSmokeResult | null = null;
  /** De-duplicates concurrent `verifySlicing()` callers onto one child process. */
  private smokeInFlight: Promise<OrcaRuntimeStatus> | null = null;

  constructor(private readonly config: OrcaCliConfig) {
    this.workerVersion = config.workerVersion;
    this.pinnedVersion = config.pinnedVersion;
    this.logger = config.logger ?? {};
  }

  /**
   * Diagnoses the runtime in stages, reporting the *first* thing that is wrong so
   * the operator gets an actionable reason rather than a generic "недоступен".
   * Never slices: it reuses the cached {@link verifySlicing} result when there is
   * one, and reports `smoke: null` when capability has not been proven yet.
   */
  async probe(): Promise<OrcaRuntimeStatus> {
    const base: OrcaRuntimeStatus = {
      available: false,
      state: "not_configured",
      binaryPath: this.config.command,
      detectedVersion: null,
      cliBuild: null,
      resourcesVersion: null,
      pinnedVersion: this.pinnedVersion,
      versionMatches: null,
      networkIsolated: this.config.networkIsolated ?? false,
      error: null,
      detail: null,
      smoke: this.smoke,
      workerVersion: this.workerVersion
    };

    // ── 1. Configured at all? ────────────────────────────────────────────────
    if (!this.config.command) {
      return { ...base, error: "OrcaSlicer не настроен (ORCA_SLICER_CMD не задан)" };
    }

    // ── 2. The file on disk (only when the command is a path, not `docker`) ──
    const fileFault = this.inspectExecutable();
    if (fileFault) return { ...base, ...fileFault };

    // ── 3. The process starts and speaks OrcaSlicer ──────────────────────────
    let out: CliResult;
    try {
      out = await this.run([...(this.config.baseArgs ?? []), "--help"], {
        timeoutMs: 30000,
        cwd: process.cwd()
      });
    } catch (error) {
      const message = (error as Error).message;
      const missingBinary = /ENOENT/.test(message);
      return {
        ...base,
        state: missingBinary ? "executable_missing" : "cli_incompatible",
        error: missingBinary
          ? `OrcaSlicer не найден по пути ${this.config.command}`
          : "OrcaSlicer не удалось запустить",
        detail: message
      };
    }

    const output = `${out.stdout}\n${out.stderr}`;
    // A dynamic-link failure is its own diagnosis: the binary is fine, the image is
    // missing the GTK/WebKit stack it links against (the lean image does).
    const loaderError = /error while loading shared libraries: (\S+)/.exec(output);
    if (loaderError) {
      return {
        ...base,
        state: "runtime_dependency_missing",
        error: `OrcaSlicer не запускается: нет системной библиотеки ${loaderError[1]}`,
        detail: tail(output, 400)
      };
    }
    if (out.exitCode !== 0) {
      return {
        ...base,
        state: "cli_incompatible",
        error: `OrcaSlicer не принял «--help» (код ${out.exitCode})`,
        detail: tail(output, 400)
      };
    }

    const cliBuild = BANNER_RE.exec(output)?.[1] ?? null;
    if (!cliBuild) {
      return {
        ...base,
        state: "cli_incompatible",
        error: "Это не OrcaSlicer CLI — в выводе «--help» нет баннера OrcaSlicer",
        detail: tail(output, 400)
      };
    }

    // ── 4. The CLI supports the flags this worker actually uses ──────────────
    const missingFlags = REQUIRED_FLAGS.filter((flag) => !output.includes(flag));
    if (missingFlags.length > 0) {
      return {
        ...base,
        cliBuild,
        state: "cli_incompatible",
        error: `CLI OrcaSlicer не поддерживает: ${missingFlags.join(", ")}`,
        detail: `сборка ${cliBuild}; отсутствуют флаги ${missingFlags.join(", ")}`
      };
    }

    // ── 5. Resources beside the binary, and the version they belong to ───────
    const resourcesVersion = this.readResourcesVersion();
    const withCli = { ...base, cliBuild, resourcesVersion };
    // Only complain when the deployment actually *declared* it resolves parents out
    // of this runtime's own tree (that dir is in the smoke roots). A lean install
    // that resolves purely from the operator `vendor/` closure is a supported shape,
    // not a fault — and in container mode the resources live inside the image where
    // this process cannot see them at all.
    const resourcesDir = this.resourcesProfilesDir();
    const expectsBundledResources = Boolean(
      resourcesDir && this.config.smokeProfileRoots?.some((root) => path.resolve(root) === resourcesDir)
    );
    if (expectsBundledResources && !fs.existsSync(resourcesDir as string)) {
      return {
        ...withCli,
        state: "resources_missing",
        error: "Рядом с OrcaSlicer нет дерева resources/profiles — наследование профилей не разрешится",
        detail: `ожидалось ${resourcesDir}`
      };
    }

    // ── 6. Capability: the last real slice, plus the version binding ─────────
    const detectedVersion = this.smoke?.releaseVersion ?? resourcesVersion;
    const versionMatches =
      this.pinnedVersion && detectedVersion ? matchesPinned(detectedVersion, this.pinnedVersion) : null;

    if (versionMatches === false) {
      return {
        ...withCli,
        detectedVersion,
        versionMatches,
        state: "version_mismatch",
        error: `Версия OrcaSlicer ${detectedVersion} не совпадает с закреплённой ${this.pinnedVersion}`,
        detail: `сборка CLI ${cliBuild}; resources ${resourcesVersion ?? "?"}; двоичный файл ${this.smoke?.releaseVersion ?? "?"}`
      };
    }

    // Binary and resources must agree — a half-replaced install is exactly the kind
    // of thing that otherwise surfaces as a corrupt print.
    if (
      this.smoke?.releaseVersion &&
      resourcesVersion &&
      !matchesPinned(this.smoke.releaseVersion, resourcesVersion)
    ) {
      return {
        ...withCli,
        detectedVersion,
        versionMatches,
        state: "version_mismatch",
        error: `Двоичный файл OrcaSlicer ${this.smoke.releaseVersion} не совпадает с resources ${resourcesVersion}`,
        detail: "смешанная установка: бинарь и профили из разных релизов"
      };
    }

    if (this.smoke && !this.smoke.ok) {
      return {
        ...withCli,
        detectedVersion,
        versionMatches,
        state: "smoke_failed",
        error: "OrcaSlicer запускается, но пробный слайсинг не дал G-code",
        detail: this.smoke.error
      };
    }

    return {
      ...withCli,
      detectedVersion,
      versionMatches,
      state: "ready",
      available: true,
      error: null
    };
  }

  /**
   * Proves the runtime by slicing the smoke fixture for real, and caches the result
   * so later `probe()` calls are free. Concurrent callers share one run.
   */
  async verifySlicing(options: { force?: boolean; signal?: AbortSignal } = {}): Promise<OrcaRuntimeStatus> {
    if (this.smoke && !options.force) return this.probe();
    if (this.smokeInFlight) return this.smokeInFlight;
    this.smokeInFlight = this.runSmoke(options.signal).finally(() => {
      this.smokeInFlight = null;
    });
    return this.smokeInFlight;
  }

  private async runSmoke(signal?: AbortSignal): Promise<OrcaRuntimeStatus> {
    // Only worth attempting once the cheap stages pass — otherwise the smoke's
    // failure would mask the real (and more specific) diagnosis.
    const pre = await this.probe();
    if (pre.state !== "ready" && pre.state !== "smoke_failed") return pre;

    const roots = this.config.smokeProfileRoots ?? [];
    const fixture: SmokeFixture | null = buildSmokeFixture(roots);
    if (!fixture) {
      this.logger.warn?.(
        { roots },
        "orca smoke fixture not found in any profile root — capability left unverified"
      );
      return pre;
    }

    const started = Date.now();
    const workDir = await fsp.mkdtemp(path.join(os.tmpdir(), "orca-smoke-"));
    try {
      const machinePath = path.join(workDir, "machine.json");
      const processPath = path.join(workDir, "process.json");
      const filamentPath = path.join(workDir, "filament.json");
      const modelPath = path.join(workDir, "smoke.stl");
      const { machine } = applyCliCompatShims(fixture.machine);
      await fsp.writeFile(machinePath, JSON.stringify(machine), "utf8");
      await fsp.writeFile(processPath, JSON.stringify(fixture.process), "utf8");
      await fsp.writeFile(filamentPath, JSON.stringify(fixture.filament), "utf8");
      await fsp.writeFile(modelPath, fixture.model);

      const result = await this.run(
        this.sliceArgs({
          machineJsonPath: machinePath,
          processJsonPath: processPath,
          filamentJsonPath: filamentPath,
          modelPath,
          workDir
        }),
        { timeoutMs: 120000, cwd: workDir, signal }
      );

      const produced = await this.locateOutput({
        machineJsonPath: machinePath,
        processJsonPath: processPath,
        filamentJsonPath: filamentPath,
        modelPath,
        workDir,
        outputPath: path.join(workDir, "__none__")
      });
      const gcode = produced ? await fsp.readFile(produced, "utf8").catch(() => "") : "";
      const ok = result.exitCode === 0 && gcode.length > 0;

      this.smoke = {
        ok,
        releaseVersion: GCODE_VERSION_RE.exec(gcode.slice(0, 4096))?.[1] ?? null,
        gcodeBytes: gcode.length,
        durationMs: Date.now() - started,
        error: ok
          ? null
          : `${result.signal ? `аварийное завершение ${result.signal}` : `код ${result.exitCode}`}: ` +
            `${tail(result.stderr || result.stdout, 300) || "G-code не создан"}`,
        checkedAt: new Date().toISOString()
      };
      this.logger.info?.(
        { ok, release: this.smoke.releaseVersion, bytes: this.smoke.gcodeBytes, ms: this.smoke.durationMs },
        "orca smoke slice finished"
      );
    } catch (error) {
      this.smoke = {
        ok: false,
        releaseVersion: null,
        gcodeBytes: 0,
        durationMs: Date.now() - started,
        error: (error as Error).message,
        checkedAt: new Date().toISOString()
      };
    } finally {
      await fsp.rm(workDir, { recursive: true, force: true }).catch(() => {
        /* best effort */
      });
    }
    return this.probe();
  }

  /** True when `command` names a file we can stat (not `docker`/`podman`). */
  private isPathCommand(): boolean {
    return Boolean(this.config.command?.includes(path.sep));
  }

  /** `/opt/orca/AppRun` → `/opt/orca/resources/profiles`; null in container mode. */
  private resourcesProfilesDir(): string | null {
    if (!this.isPathCommand()) return null;
    return path.resolve(path.dirname(this.config.command as string), "resources", "profiles");
  }

  /**
   * The OrcaSlicer release the bundled system profiles belong to. Vendor bundles
   * carry `"version": "02.03.00.03"`, whose first three fields track the release —
   * so a 2.3.0 tree reads back as `2.3.0`. Bambu's own `BBL.json` is deliberately
   * skipped: it keeps the upstream BambuStudio number (`01.10.00.35`) in every Orca
   * release, and reading *that* is what produced the phantom "1.10.1" this runtime
   * was mistakenly pinned to.
   */
  private readResourcesVersion(): string | null {
    const dir = this.resourcesProfilesDir();
    if (!dir) return null;
    let entries: string[];
    try {
      entries = fs.readdirSync(dir).filter((f) => f.toLowerCase().endsWith(".json") && f !== "BBL.json");
    } catch {
      return null;
    }
    const counts = new Map<string, number>();
    for (const entry of entries) {
      let head: string;
      try {
        head = fs.readFileSync(path.join(dir, entry), "utf8").slice(0, 512);
      } catch {
        continue;
      }
      const raw = VENDOR_VERSION_RE.exec(head)?.[1];
      if (!raw) continue;
      const release = normalizeVersion(raw).split(".").slice(0, 3).join(".");
      counts.set(release, (counts.get(release) ?? 0) + 1);
    }
    if (counts.size === 0) return null;
    // The release the *majority* of vendors agree on; a stray outlier never wins.
    return [...counts.entries()].sort((a, b) => b[1] - a[1])[0][0];
  }

  /** Stats the configured executable; returns a fault when it cannot be run. */
  private inspectExecutable(): Partial<OrcaRuntimeStatus> | null {
    if (!this.isPathCommand()) return null; // container runtime — resolved via PATH
    const command = this.config.command as string;
    let stat: fs.Stats;
    try {
      stat = fs.statSync(command);
    } catch {
      return {
        state: "executable_missing" as OrcaRuntimeState,
        error: `OrcaSlicer не найден по пути ${command}`,
        detail: "путь не существует — проверьте ORCA_HOST_DIR и монтирование /opt/orca"
      };
    }
    if (stat.isFile() && stat.size === 0) {
      return {
        state: "executable_corrupted" as OrcaRuntimeState,
        error: `Файл OrcaSlicer пуст (0 байт): ${command}`,
        detail: "установка оборвалась — распакуйте AppImage заново"
      };
    }
    try {
      fs.accessSync(command, fs.constants.X_OK);
    } catch {
      return {
        state: "executable_corrupted" as OrcaRuntimeState,
        error: `Файл OrcaSlicer не исполняемый: ${command}`,
        detail: `права ${(stat.mode & 0o777).toString(8)}`
      };
    }
    return null;
  }

  async slice(req: SliceRequest, options: SliceRunOptions = {}): Promise<SliceRunOutput> {
    // The availability + version-pin gate runs ONCE per slice operation. The caller
    // (SliceService) probes before every slice and hands the result in via `probed`,
    // so we don't spawn a redundant second `--version`; a direct caller that omits it
    // still gets probed here, so the "never slice against a missing/mismatched
    // runtime" guarantee is never weakened.
    const status = options.probed ?? (await this.probe());
    if (!status.available) {
      throw new SliceRuntimeUnavailableError(status.error ?? "OrcaSlicer недоступен");
    }

    // Rewrite the machine JSON in place with any CLI-version workarounds applied.
    // The file lives in this slice's private work dir, so the operator's stored
    // profile is untouched — only what this one CLI invocation sees changes.
    await this.applyMachineShims(req.machineJsonPath);

    const args = this.sliceArgs(req);

    const started = Date.now();
    const result = await this.run(args, {
      timeoutMs: options.timeoutMs ?? 300000,
      cwd: req.workDir,
      signal: options.signal
    });
    const durationMs = Date.now() - started;

    if (result.signal || result.exitCode !== 0) {
      throw new SliceProcessError(describeExit(result, path.basename(req.modelPath)));
    }

    const produced = await this.locateOutput(req);
    if (!produced) {
      throw new SliceProcessError("OrcaSlicer не создал выходной файл");
    }
    if (produced !== req.outputPath) {
      await fsp.rename(produced, req.outputPath);
    }

    return {
      outputPath: req.outputPath,
      stdout: result.stdout,
      stderr: result.stderr,
      exitCode: result.exitCode,
      durationMs
    };
  }

  /** The exact argv this worker drives the CLI with — shared by slices and the smoke. */
  private sliceArgs(req: Omit<SliceRequest, "outputPath">): string[] {
    return [
      ...(this.config.baseArgs ?? []),
      "--load-settings",
      `${req.machineJsonPath};${req.processJsonPath}`,
      "--load-filaments",
      req.filamentJsonPath,
      "--slice",
      "0",
      "--outputdir",
      req.workDir,
      ...(this.config.extraArgs ?? []),
      req.modelPath
    ];
  }

  /**
   * Applies {@link applyCliCompatShims} to the machine JSON the caller staged. A
   * malformed file is left alone: the CLI's own error is a better diagnosis than
   * anything this could invent.
   */
  private async applyMachineShims(machineJsonPath: string): Promise<void> {
    let machine: Record<string, unknown>;
    try {
      const parsed: unknown = JSON.parse(await fsp.readFile(machineJsonPath, "utf8"));
      if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) return;
      machine = parsed as Record<string, unknown>;
    } catch {
      return;
    }
    const { machine: patched, applied } = applyCliCompatShims(machine);
    if (applied.length === 0) return;
    await fsp.writeFile(machineJsonPath, JSON.stringify(patched), "utf8");
    this.logger.info?.(
      { shims: applied.map((s) => s.id) },
      "applied OrcaSlicer CLI compatibility shims to machine config"
    );
  }

  /** Finds the sliced artifact the CLI produced in the work dir (newest .gcode/.3mf). */
  private async locateOutput(req: SliceRequest): Promise<string | null> {
    if (fs.existsSync(req.outputPath)) return req.outputPath;
    let entries: string[];
    try {
      entries = await fsp.readdir(req.workDir);
    } catch {
      return null;
    }
    const inputs = new Set(
      [req.machineJsonPath, req.processJsonPath, req.filamentJsonPath, req.modelPath].map((p) =>
        path.basename(p)
      )
    );
    const candidates = entries
      .filter((name) => /\.(gcode|gcode\.3mf|3mf)$/i.test(name) && !inputs.has(name))
      .map((name) => path.join(req.workDir, name));
    if (candidates.length === 0) return null;
    // Newest by mtime — the just-written slice.
    let best: { path: string; mtime: number } | null = null;
    for (const p of candidates) {
      try {
        const stat = await fsp.stat(p);
        if (!best || stat.mtimeMs > best.mtime) best = { path: p, mtime: stat.mtimeMs };
      } catch {
        /* skip */
      }
    }
    return best?.path ?? null;
  }

  /**
   * Spawns the configured command with no shell, a minimal environment, and a hard
   * timeout that kills the child if it overruns. Rejects with {@link SliceTimeoutError}
   * on timeout/abort; resolves with captured output otherwise.
   */
  private run(
    args: string[],
    opts: { timeoutMs: number; cwd: string; signal?: AbortSignal }
  ): Promise<{ stdout: string; stderr: string; exitCode: number | null; signal: NodeJS.Signals | null }> {
    const command = this.config.command as string;
    return new Promise((resolve, reject) => {
      const child = spawn(command, args, {
        cwd: opts.cwd,
        shell: false, // never a shell — paths cannot be interpreted/injected
        windowsHide: true,
        env: {
          // A minimal environment: no inherited secrets, just enough to run a GUI-less CLI.
          PATH: process.env.PATH ?? "/usr/local/bin:/usr/bin:/bin",
          HOME: opts.cwd,
          TMPDIR: opts.cwd,
          ...(process.env.DISPLAY ? {} : { QT_QPA_PLATFORM: "offscreen" })
        }
      });

      let stdout = "";
      let stderr = "";
      let settled = false;
      const finish = (fn: () => void): void => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        if (opts.signal) opts.signal.removeEventListener("abort", onAbort);
        fn();
      };

      const timer = setTimeout(() => {
        child.kill("SIGKILL");
        finish(() => reject(new SliceTimeoutError(`Превышен лимит времени слайсинга (${opts.timeoutMs} мс)`)));
      }, opts.timeoutMs);

      const onAbort = (): void => {
        child.kill("SIGKILL");
        finish(() => reject(new SliceTimeoutError("Слайсинг отменён")));
      };
      if (opts.signal) {
        if (opts.signal.aborted) {
          child.kill("SIGKILL");
          finish(() => reject(new SliceTimeoutError("Слайсинг отменён")));
          return;
        }
        opts.signal.addEventListener("abort", onAbort, { once: true });
      }

      child.stdout?.on("data", (chunk: Buffer) => {
        stdout += chunk.toString("utf8");
      });
      child.stderr?.on("data", (chunk: Buffer) => {
        stderr += chunk.toString("utf8");
      });
      child.on("error", (error) => {
        finish(() => reject(error));
      });
      child.on("close", (code, signal) => {
        // A SIGKILL here is our own timeout/abort handler, which has already settled
        // the promise with a SliceTimeoutError — `finish` makes this a no-op.
        finish(() => resolve({ stdout, stderr, exitCode: code, signal }));
      });
    });
  }
}

/** Detected version satisfies the pin when they are equal or the pin is a prefix. */
function matchesPinned(detected: string, pinned: string): boolean {
  const d = normalizeVersion(detected);
  const p = normalizeVersion(pinned);
  return d === p || d.startsWith(`${p}.`) || p.startsWith(`${d}.`);
}

/** Normalises OrcaSlicer's `02.03.00.62` and `2.3.0` forms to a comparable string. */
function normalizeVersion(v: string): string {
  return v
    .split(".")
    .map((part) => String(Number.parseInt(part, 10)))
    .join(".");
}

/** One CLI invocation's outcome. `exitCode: null` means it died on a signal. */
interface CliResult {
  stdout: string;
  stderr: string;
  exitCode: number | null;
  signal?: NodeJS.Signals | null;
}

/** Signals that mean the slicer itself crashed, as opposed to being told to stop. */
const CRASH_SIGNALS = new Set<string>(["SIGSEGV", "SIGABRT", "SIGBUS", "SIGILL", "SIGFPE"]);

/**
 * A failure message an operator can act on. A signal death is named as such —
 * killed by a signal there is no exit code and usually no stderr at all, so the
 * bare `код null` this used to report told nobody anything. OrcaSlicer 2.3.0 really
 * does segfault on some individual 3MF files (reproducible with models it ships
 * itself) while slicing everything else fine, so naming the signal *and* the model
 * is the difference between "our runtime is broken" and "this one file crashes the
 * slicer" — two conclusions with completely different repairs.
 */
function describeExit(result: CliResult, modelName?: string): string {
  const output = tail(result.stderr || result.stdout);
  const on = modelName ? ` на модели «${modelName}»` : "";
  if (result.signal) {
    return (
      `OrcaSlicer аварийно завершился (${result.signal})${on}` +
      (CRASH_SIGNALS.has(result.signal)
        ? " — упал сам слайсер, профили и среда ни при чём; попробуйте другой файл (STL или пересохранённый 3MF)"
        : "") +
      (output ? `: ${output}` : "")
    );
  }
  return `OrcaSlicer завершился с кодом ${result.exitCode}${on}: ${output}`;
}

function tail(text: string, max = 400): string {
  const trimmed = text.trim();
  return trimmed.length > max ? `…${trimmed.slice(-max)}` : trimmed;
}
