import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { after, before, test } from "node:test";

import { OrcaCliRunner } from "./orcaCliRunner";
import { SliceProcessError, SliceRuntimeUnavailableError, SliceTimeoutError } from "./sliceRunner";

/*
 * Exercises the REAL spawn-based runner (no OrcaSlicer needed) by pointing it at
 * small Node scripts that stand in for the CLI.
 *
 * The stand-ins reproduce the genuine OrcaSlicer 2.3.0 CLI contract, because that
 * contract is what the old probe got wrong:
 *
 *   - there is **no `--version` option** — the CLI answers `Invalid option --version`
 *     and exits 254, while `--help` exits 0 and slicing works fine;
 *   - the `--help` banner prints the inherited BambuStudio build id
 *     (`OrcaSlicer-01.10.01.50`), never the 2.3.0 release name;
 *   - the release is only discoverable from the G-code the slicer writes.
 *
 * Treating that 254 as "binary incompatible or built without CLI" is what made a
 * healthy install report itself unavailable, so the regression is pinned below.
 */

let TMP: string;
const NODE = process.execPath;

/** The real 2.3.0 `--help` output, trimmed to the parts the probe reads. */
const HELP_BANNER = `OrcaSlicer-01.10.01.50:
Usage: orca-slicer [ OPTIONS ] [ file.3mf/file.stl ... ]

OPTIONS:
 --load-settings "setting1.json;setting2.json"
 --load-filaments "filament1.json;filament2.json;..."
 --outputdir dir     Output directory for the exported files.
 --slice option      Slice the plates: 0-all plates, i-plate i, others-invalid
`;

/**
 * A faithful stand-in: rejects `--version` exactly as OrcaSlicer does, answers
 * `--help`, and otherwise slices (writes a plate G-code carrying the release).
 */
const FAKE_ORCA = `
const fs = require("fs");
const path = require("path");
const args = process.argv.slice(2);
if (args.includes("--version")) {
  console.log(${JSON.stringify(HELP_BANNER)});
  console.error("Invalid option --version\\n\\nsetup params error");
  process.exit(254);
}
if (args.includes("--help")) { console.log(${JSON.stringify(HELP_BANNER)}); process.exit(0); }
const oi = args.indexOf("--outputdir");
fs.writeFileSync(path.join(args[oi + 1], "plate_1.gcode"),
  "; generated by OrcaSlicer 2.3.0 on 2026-08-14\\nG1 X0 Y0 E1\\n");
process.exit(0);
`;

/** Answers `--help`, then hangs on a slice so the wall-clock kill can fire. */
const SLOW_ORCA = `
const args = process.argv.slice(2);
if (args.includes("--help")) { console.log(${JSON.stringify(HELP_BANNER)}); process.exit(0); }
setTimeout(() => process.exit(0), 60000);
`;

/** A CLI whose help lacks the flags this worker drives it with. */
const WRONG_CLI = `
console.log("OrcaSlicer-01.10.01.50:\\nUsage: orca-slicer\\n --export-3mf file.3mf");
process.exit(0);
`;

/** Something that runs but is not OrcaSlicer at all. */
const NOT_ORCA = `console.log("PrusaSlicer 2.7.4"); process.exit(0);`;

/** A binary that cannot start because the image lacks its shared libraries. */
const MISSING_LIBS = `
console.error("/opt/orca/bin/orca-slicer: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory");
process.exit(127);
`;

/** Slices successfully only after the first attempt fails (retry-after-error). */
const FLAKY_ORCA = `
const fs = require("fs");
const path = require("path");
const args = process.argv.slice(2);
if (args.includes("--help")) { console.log(${JSON.stringify(HELP_BANNER)}); process.exit(0); }
const marker = __filename + ".failed";
if (!fs.existsSync(marker)) {
  fs.writeFileSync(marker, "1");
  console.error("got error when validate: something went wrong");
  process.exit(205);
}
const oi = args.indexOf("--outputdir");
fs.writeFileSync(path.join(args[oi + 1], "plate_1.gcode"), "; generated by OrcaSlicer 2.3.0\\nG1 X0 Y0 E1\\n");
process.exit(0);
`;

/** Dies on SIGSEGV, as OrcaSlicer 2.3.0 really does on some 3MF inputs. */
const SEGFAULT_ORCA = `
const args = process.argv.slice(2);
if (args.includes("--help")) { console.log(${JSON.stringify(HELP_BANNER)}); process.exit(0); }
process.kill(process.pid, "SIGSEGV");
`;

/** Records every argv it was given, so command construction can be asserted. */
const RECORD_ORCA = `
const fs = require("fs");
const path = require("path");
const args = process.argv.slice(2);
if (args.includes("--help")) { console.log(${JSON.stringify(HELP_BANNER)}); process.exit(0); }
fs.appendFileSync(__filename + ".argv", JSON.stringify(args) + "\\n");
const oi = args.indexOf("--outputdir");
fs.writeFileSync(path.join(args[oi + 1], "plate_1.gcode"), "; generated by OrcaSlicer 2.3.0\\nG1 X0 Y0 E1\\n");
process.exit(0);
`;

const scripts: Record<string, string> = {};
/** A profile root carrying the stock chain {@link buildSmokeFixture} looks for. */
let FIXTURE_ROOT: string;

function write(name: string, body: string): string {
  const p = path.join(TMP, name);
  fs.writeFileSync(p, body);
  return p;
}

/** Writes the stock Bambu A1 triple the smoke fixture resolves, under `root`. */
function writeFixtureChain(root: string): string {
  for (const [kind, name] of [
    ["machine", "Bambu Lab A1 0.4 nozzle"],
    ["process", "0.20mm Standard @BBL A1"],
    ["filament", "Bambu PLA Basic @BBL A1"]
  ] as const) {
    const dir = path.join(root, "BBL", kind);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, `${name}.json`), JSON.stringify({ type: kind, from: "system" }));
  }
  return root;
}

before(() => {
  TMP = fs.mkdtempSync(path.join(os.tmpdir(), "orca-cli-"));
  scripts.fake = write("fake-orca.js", FAKE_ORCA);
  scripts.slow = write("slow-orca.js", SLOW_ORCA);
  scripts.wrongCli = write("wrong-cli.js", WRONG_CLI);
  scripts.notOrca = write("not-orca.js", NOT_ORCA);
  scripts.missingLibs = write("missing-libs.js", MISSING_LIBS);
  scripts.flaky = write("flaky-orca.js", FLAKY_ORCA);
  scripts.record = write("record-orca.js", RECORD_ORCA);
  scripts.segfault = write("segfault-orca.js", SEGFAULT_ORCA);
  FIXTURE_ROOT = writeFixtureChain(path.join(TMP, "fixture-root"));
});
after(() => {
  fs.rmSync(TMP, { recursive: true, force: true });
});

/**
 * Lays out a fake install the way a real one sits on disk — an executable at
 * `<home>/AppRun` with its `resources/profiles` tree beside it — because that
 * adjacency is exactly what the binary↔resources version binding reads.
 */
function installFakeOrca(
  home: string,
  script: string,
  vendors: Record<string, string> = {}
): string {
  fs.mkdirSync(home, { recursive: true });
  const appRun = path.join(home, "AppRun");
  fs.writeFileSync(appRun, `#!/bin/sh\nexec ${JSON.stringify(NODE)} ${JSON.stringify(script)} "$@"\n`);
  fs.chmodSync(appRun, 0o755);
  const entries = Object.entries(vendors);
  if (entries.length > 0) {
    const profiles = path.join(home, "resources", "profiles");
    fs.mkdirSync(profiles, { recursive: true });
    for (const [vendor, version] of entries) {
      fs.writeFileSync(path.join(profiles, `${vendor}.json`), JSON.stringify({ name: vendor, version }));
    }
  }
  return appRun;
}

function runner(script: string, overrides: Record<string, unknown> = {}): OrcaCliRunner {
  return new OrcaCliRunner({
    command: NODE,
    baseArgs: [script],
    pinnedVersion: "2.3.0",
    workerVersion: "w1",
    ...overrides
  } as ConstructorParameters<typeof OrcaCliRunner>[0]);
}

function req(workDir: string, machine: Record<string, unknown> = {}) {
  fs.mkdirSync(workDir, { recursive: true });
  const put = (name: string, body: string): string => {
    const p = path.join(workDir, name);
    fs.writeFileSync(p, body);
    return p;
  };
  return {
    modelPath: put("model.stl", "solid x"),
    machineJsonPath: put("machine.json", JSON.stringify(machine)),
    processJsonPath: put("process.json", "{}"),
    filamentJsonPath: put("filament.json", "{}"),
    outputPath: path.join(workDir, "out.gcode"),
    workDir
  };
}

// ── probe: the states an operator has to tell apart ──────────────────────────

test("probe() accepts a CLI that has no --version but a working --help (the regression)", async () => {
  // The real OrcaSlicer 2.3.0 exits 254 on `--version`. That must NOT be read as a
  // broken binary: this exact misreading blocked every slice on a healthy install.
  const status = await runner(scripts.fake).probe();
  assert.equal(status.available, true);
  assert.equal(status.state, "ready");
  assert.equal(status.error, null);
});

test("probe() reports the banner build id separately from the release", async () => {
  const status = await runner(scripts.fake).probe();
  // The banner's 01.10.01.50 is BambuStudio lineage — it must never be mistaken for
  // the release, nor compared against the pin.
  assert.equal(status.cliBuild, "01.10.01.50");
  assert.notEqual(status.detectedVersion, "01.10.01.50");
});

test("probe() with no command configured is unavailable with a clear message", async () => {
  const status = await new OrcaCliRunner({
    command: null,
    pinnedVersion: "2.3.0",
    workerVersion: "w1"
  }).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "not_configured");
  assert.match(status.error ?? "", /не настроен|ORCA_SLICER_CMD/);
});

test("probe() distinguishes a MISSING executable", async () => {
  const status = await new OrcaCliRunner({
    command: path.join(TMP, "does-not-exist"),
    pinnedVersion: null,
    workerVersion: "w1"
  }).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "executable_missing");
});

test("probe() distinguishes a CORRUPTED (0-byte) executable", async () => {
  // Exactly the shape a truncated download / out-of-disk extraction leaves behind.
  const empty = path.join(TMP, "empty-orca");
  fs.writeFileSync(empty, "");
  fs.chmodSync(empty, 0o755);
  const status = await new OrcaCliRunner({
    command: empty,
    pinnedVersion: null,
    workerVersion: "w1"
  }).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "executable_corrupted");
  assert.match(status.error ?? "", /0 байт/);
});

test("probe() distinguishes a non-executable file", async () => {
  const noExec = path.join(TMP, "noexec-orca");
  fs.writeFileSync(noExec, "#!/bin/sh\necho hi\n");
  fs.chmodSync(noExec, 0o644);
  const status = await new OrcaCliRunner({
    command: noExec,
    pinnedVersion: null,
    workerVersion: "w1"
  }).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "executable_corrupted");
});

test("probe() distinguishes missing shared libraries from a bad binary", async () => {
  const status = await runner(scripts.missingLibs).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "runtime_dependency_missing");
  assert.match(status.error ?? "", /libwebkit2gtk-4\.0\.so\.37/);
});

test("probe() rejects a CLI missing the flags this worker uses", async () => {
  const status = await runner(scripts.wrongCli).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "cli_incompatible");
  assert.match(status.error ?? "", /--load-settings/);
});

test("probe() rejects something that is not OrcaSlicer at all", async () => {
  const status = await runner(scripts.notOrca).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "cli_incompatible");
  assert.match(status.error ?? "", /не OrcaSlicer/i);
});

test("probe() reports resources_missing only when the runtime's own tree was expected", async () => {
  const expected = path.resolve(path.dirname(NODE), "resources", "profiles");
  const status = await runner(scripts.fake, { smokeProfileRoots: [expected] }).probe();
  assert.equal(status.state, "resources_missing");
  assert.equal(status.available, false);

  // Without that declaration the same runtime is fine — resolving parents purely
  // from the operator `vendor/` closure is a supported deployment shape.
  const lean = await runner(scripts.fake, { smokeProfileRoots: [path.join(TMP, "vendor")] }).probe();
  assert.equal(lean.state, "ready");
});

// ── version pinning + binary/resources binding ───────────────────────────────

test("probe() reports a version mismatch against the pin honestly", async () => {
  const appRun = installFakeOrca(path.join(TMP, "pin"), scripts.fake, { Anker: "02.03.00.03" });
  const status = await new OrcaCliRunner({
    command: appRun,
    pinnedVersion: "9.9.9",
    workerVersion: "w1"
  }).probe();
  assert.equal(status.available, false);
  assert.equal(status.state, "version_mismatch");
  assert.equal(status.versionMatches, false);
  assert.match(status.error ?? "", /9\.9\.9/);
});

test("probe() catches a binary/resources split-version install", async () => {
  // The binary really is 2.3.0 (its G-code says so); the tree beside it is 2.1.x —
  // a half-replaced install, which must be caught before it reaches a printer.
  const appRun = installFakeOrca(path.join(TMP, "split"), scripts.fake, { Anker: "02.01.00.03" });
  const r = new OrcaCliRunner({
    command: appRun,
    pinnedVersion: null,
    workerVersion: "w1",
    smokeProfileRoots: [FIXTURE_ROOT]
  });
  await r.verifySlicing(); // learns the binary's release from the produced G-code
  const status = await r.probe();
  assert.equal(status.resourcesVersion, "2.1.0");
  assert.equal(status.smoke?.releaseVersion, "2.3.0");
  assert.equal(status.state, "version_mismatch");
  assert.match(status.error ?? "", /resources/i);
});

test("readResourcesVersion ignores BBL.json, whose version is BambuStudio lineage", async () => {
  // BBL.json legitimately reads "01.10.00.35" in every OrcaSlicer release; letting
  // it win is how this deployment ended up pinned to a nonexistent "1.10.1".
  const appRun = installFakeOrca(path.join(TMP, "bblskip"), scripts.fake, {
    BBL: "01.10.00.35",
    Anker: "02.03.00.03",
    Creality: "02.03.00.03",
    Elegoo: "02.03.00.03"
  });
  const status = await new OrcaCliRunner({
    command: appRun,
    pinnedVersion: "2.3.0",
    workerVersion: "w1"
  }).probe();
  assert.equal(status.resourcesVersion, "2.3.0");
  assert.equal(status.state, "ready");
});

// ── verifySlicing: capability proven by real G-code ──────────────────────────

test("verifySlicing() with no fixture leaves capability unverified but does not lie", async () => {
  const r = runner(scripts.fake, { smokeProfileRoots: [path.join(TMP, "nowhere")] });
  const status = await r.verifySlicing();
  assert.equal(status.smoke, null, "no fixture ⇒ nothing was proven");
  assert.equal(status.available, true, "…and the cheap checks still stand on their own");
});

test("verifySlicing() slices a real fixture and learns the release from its G-code", async () => {
  const r = runner(scripts.fake, { smokeProfileRoots: [FIXTURE_ROOT] });
  const status = await r.verifySlicing();
  assert.equal(status.smoke?.ok, true);
  assert.ok((status.smoke?.gcodeBytes ?? 0) > 0);
  // The release comes from the produced G-code header — the only honest source.
  assert.equal(status.smoke?.releaseVersion, "2.3.0");
  assert.equal(status.detectedVersion, "2.3.0");
  assert.equal(status.state, "ready");
});

test("a failing smoke slice makes the runtime unavailable with smoke_failed", async () => {
  // A CLI that answers --help but never produces G-code.
  const broken = write("broken-slice.js", `
const args = process.argv.slice(2);
if (args.includes("--help")) { console.log(${JSON.stringify(HELP_BANNER)}); process.exit(0); }
console.error("got error when validate: relative extruder addressing…");
process.exit(205);
`);
  const r = runner(broken, { smokeProfileRoots: [FIXTURE_ROOT] });
  const status = await r.verifySlicing();
  assert.equal(status.state, "smoke_failed");
  assert.equal(status.available, false);
  assert.equal(status.smoke?.ok, false);
  assert.match(status.detail ?? "", /205/);
});

// ── slicing ──────────────────────────────────────────────────────────────────

test("slice() runs the process and relocates the produced plate to outputPath", async () => {
  const request = req(path.join(TMP, "job-ok"));
  const result = await runner(scripts.fake).slice(request, { timeoutMs: 20000 });
  assert.equal(result.outputPath, request.outputPath);
  assert.equal(result.exitCode, 0);
  assert.ok(fs.existsSync(request.outputPath));
  assert.match(fs.readFileSync(request.outputPath, "utf8"), /OrcaSlicer/);
});

test("slice() builds the exact CLI command OrcaSlicer expects", async () => {
  fs.rmSync(`${scripts.record}.argv`, { force: true });
  const request = req(path.join(TMP, "job-argv"));
  await runner(scripts.record).slice(request, { timeoutMs: 20000 });
  const argv: string[] = JSON.parse(fs.readFileSync(`${scripts.record}.argv`, "utf8").trim().split("\n").pop() as string);

  // `--load-settings` takes machine and process as ONE semicolon-joined argument.
  const settings = argv[argv.indexOf("--load-settings") + 1];
  assert.equal(settings, `${request.machineJsonPath};${request.processJsonPath}`);
  assert.equal(argv[argv.indexOf("--load-filaments") + 1], request.filamentJsonPath);
  assert.equal(argv[argv.indexOf("--slice") + 1], "0");
  assert.equal(argv[argv.indexOf("--outputdir") + 1], request.workDir);
  // The model is last, after every flag.
  assert.equal(argv[argv.length - 1], request.modelPath);
  // There is no `--export-gcode` in this CLI: `--slice` + `--outputdir` is the export.
  assert.ok(!argv.includes("--export-gcode"));
});

test("slice() reports a non-zero exit as a slice failure carrying the CLI's own words", async () => {
  fs.rmSync(`${scripts.flaky}.failed`, { force: true });
  const request = req(path.join(TMP, "job-flaky-1"));
  await assert.rejects(
    () => runner(scripts.flaky).slice(request, { timeoutMs: 20000 }),
    (error: Error) => error instanceof SliceProcessError && /205/.test(error.message)
  );
});

test("a slice can be retried after a failure and succeeds", async () => {
  // The first attempt above armed the failure marker; a fresh attempt must work,
  // i.e. nothing about the first failure poisons the runner.
  const request = req(path.join(TMP, "job-flaky-2"));
  const result = await runner(scripts.flaky).slice(request, { timeoutMs: 20000 });
  assert.equal(result.exitCode, 0);
  assert.ok(fs.existsSync(request.outputPath));
});

test("slice() enforces the timeout by killing the process", async () => {
  const request = req(path.join(TMP, "job-slow"));
  await assert.rejects(runner(scripts.slow).slice(request, { timeoutMs: 300 }), SliceTimeoutError);
});

test("slice() throws SliceRuntimeUnavailableError when there is no runtime", async () => {
  const r = new OrcaCliRunner({ command: null, pinnedVersion: "2.3.0", workerVersion: "w1" });
  await assert.rejects(
    r.slice(req(path.join(TMP, "job-none")), { timeoutMs: 1000 }),
    SliceRuntimeUnavailableError
  );
});

test("slice() is refused before spawning when the CLI is incompatible", async () => {
  await assert.rejects(
    () => runner(scripts.wrongCli).slice(req(path.join(TMP, "job-badcli"))),
    (error: Error) => error instanceof SliceRuntimeUnavailableError
  );
});

test("slice() applies the Bambu relative-E shim to the machine JSON it hands the CLI", async () => {
  const request = req(path.join(TMP, "job-shim"), {
    printer_model: "Bambu Lab A1",
    gcode_flavor: "marlin",
    use_relative_e_distances: "1",
    layer_change_gcode: "M73 L{layer_num+1}",
    before_layer_change_gcode: ""
  });
  await runner(scripts.fake).slice(request, { timeoutMs: 20000 });
  const patched = JSON.parse(fs.readFileSync(request.machineJsonPath, "utf8"));
  assert.match(patched.before_layer_change_gcode, /G92 E0/);
});

test("a slicer that dies on a signal is reported as a crash, not as «код null»", async () => {
  // OrcaSlicer 2.3.0 segfaults on some individual models (verified: its own bundled
  // OrcaCube_v2.3mf crashes it even with stock Bambu profiles). The old message read
  // "завершился с кодом null" and lost both the signal and the model name, which
  // reads like a broken runtime rather than one bad file.
  await assert.rejects(
    () => runner(scripts.segfault).slice(req(path.join(TMP, "job-segv")), { timeoutMs: 20000 }),
    (error: Error) => {
      assert.ok(error instanceof SliceProcessError);
      assert.match(error.message, /SIGSEGV/);
      assert.match(error.message, /model\.stl/, "names the model that crashed it");
      assert.match(error.message, /упал сам слайсер/, "and says whose fault it is");
      assert.doesNotMatch(error.message, /кодом null/);
      return true;
    }
  );
});

test("a slicer merely terminated is not blamed for crashing", async () => {
  // SIGTERM means something asked the process to stop. Handing the operator the
  // advice a SIGSEGV earns ("re-export the model") would send them after the wrong
  // problem entirely.
  const killed = write("term-orca.js", `
const args = process.argv.slice(2);
if (args.includes("--help")) { console.log(${JSON.stringify(HELP_BANNER)}); process.exit(0); }
process.kill(process.pid, "SIGTERM");
`);
  await assert.rejects(
    () => runner(killed).slice(req(path.join(TMP, "job-term")), { timeoutMs: 20000 }),
    (error: Error) => {
      assert.ok(error instanceof SliceProcessError);
      assert.match(error.message, /SIGTERM/);
      assert.doesNotMatch(error.message, /упал сам слайсер/);
      return true;
    }
  );
});
