import fs from "node:fs";
import path from "node:path";

/**
 * The fixture the runtime probe really slices.
 *
 * A capability check is only worth anything if it exercises the same path a real
 * slice takes: resolved machine/process/filament JSON handed to the CLI, which must
 * come back with G-code. So the fixture is not a synthetic minimal config — the CLI
 * rejects those anyway (it demands `from`, and enforces `compatible_printers`
 * against the *inherited system* preset name) — but a stock vendor chain resolved
 * out of the very profile roots the deployment resolves user presets against.
 *
 * That choice buys three things at once:
 *
 *   - it proves the binary slices;
 *   - it proves the resources tree beside that binary is present and coherent with
 *     it (a mismatched pair fails here, not on the operator's first real print);
 *   - the produced G-code header carries the authoritative OrcaSlicer *release*
 *     (`; generated by OrcaSlicer 2.3.0`), which is the only reliable way to learn
 *     it — the CLI banner reports the inherited BambuStudio build id instead.
 *
 * The default chain is the stock Bambu A1 triple, which ships both in the operator
 * `vendor/` closure and in OrcaSlicer's own `resources/profiles`, so the check works
 * with or without a mounted runtime. When no root carries it the probe reports the
 * fixture as unavailable and says so, rather than inventing a pass.
 */

/** A stock vendor chain, addressed the way both profile roots lay them out. */
export interface SmokeChain {
  vendor: string;
  machine: string;
  process: string;
  filament: string;
}

/** The stock Bambu A1 0.4 triple — present in `vendor/` and in `resources/profiles`. */
export const DEFAULT_SMOKE_CHAIN: SmokeChain = {
  vendor: "BBL",
  machine: "Bambu Lab A1 0.4 nozzle",
  process: "0.20mm Standard @BBL A1",
  filament: "Bambu PLA Basic @BBL A1"
};

export interface SmokeFixture {
  machine: Record<string, unknown>;
  process: Record<string, unknown>;
  filament: Record<string, unknown>;
  /** A 10 mm cube as a binary STL — small enough to slice in about a second. */
  model: Buffer;
  /** Which chain, from which root — for diagnostics. */
  chain: SmokeChain;
  root: string;
}

type Kind = "machine" | "process" | "filament";

/**
 * Resolves one stock preset and its `inherits` ancestry within a single vendor
 * folder. Vendor scoping matters: the shipped tree has dozens of same-named
 * `fdm_machine_common` files, and crossing brands would silently build a Frankenstein
 * config (see {@link SystemProfileIndex} for the same rule on the user-preset path).
 */
function resolvePreset(
  root: string,
  vendor: string,
  kind: Kind,
  name: string,
  seen = new Set<string>()
): Record<string, unknown> | null {
  if (seen.has(name)) return null; // inheritance cycle — treat as unresolvable
  seen.add(name);
  const file = path.join(root, vendor, kind, `${name}.json`);
  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) return null;
  const self = parsed as Record<string, unknown>;
  const inherits = typeof self.inherits === "string" ? self.inherits : null;
  const parent = inherits ? resolvePreset(root, vendor, kind, inherits, seen) : {};
  if (parent === null) return null;
  const merged = { ...parent, ...self };
  // A resolved preset stands alone: the CLI must not go looking for a parent it has
  // no bundle context to find.
  delete merged.inherits;
  merged.name = name;
  return merged;
}

/**
 * Builds the smoke fixture from the first root that carries the whole chain.
 * Returns null when no root does — the caller reports that as "cannot verify",
 * never as success.
 */
export function buildSmokeFixture(
  roots: readonly string[],
  chain: SmokeChain = DEFAULT_SMOKE_CHAIN
): SmokeFixture | null {
  for (const root of roots) {
    if (!root) continue;
    const machine = resolvePreset(root, chain.vendor, "machine", chain.machine);
    const process = resolvePreset(root, chain.vendor, "process", chain.process);
    const filament = resolvePreset(root, chain.vendor, "filament", chain.filament);
    if (machine && process && filament) {
      return { machine, process, filament, model: cubeStl(10), chain, root };
    }
  }
  return null;
}

/** A `size` mm cube at the origin, as a binary STL (12 triangles, 684 bytes). */
export function cubeStl(size: number): Buffer {
  const h = size / 2;
  const v: Array<[number, number, number]> = [
    [-h, -h, 0], [h, -h, 0], [h, h, 0], [-h, h, 0],
    [-h, -h, size], [h, -h, size], [h, h, size], [-h, h, size]
  ];
  const tris = [
    [0, 3, 2], [0, 2, 1], // bottom
    [4, 5, 6], [4, 6, 7], // top
    [0, 1, 5], [0, 5, 4], [1, 2, 6], [1, 6, 5],
    [2, 3, 7], [2, 7, 6], [3, 0, 4], [3, 4, 7]
  ];
  const buf = Buffer.alloc(84 + tris.length * 50);
  buf.write("atelier smoke cube", 0);
  buf.writeUInt32LE(tris.length, 80);
  let o = 84;
  for (const t of tris) {
    o += 12; // zero normal — slicers recompute it
    for (const i of t) {
      buf.writeFloatLE(v[i][0], o);
      buf.writeFloatLE(v[i][1], o + 4);
      buf.writeFloatLE(v[i][2], o + 8);
      o += 12;
    }
    o += 2; // attribute byte count
  }
  return buf;
}
